// Code generated by protoc-gen-go. DO NOT EDIT.
// source: broadcast.proto

package lugo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventDebugBreakpoint_Breakpoint int32

const (
	// Breakpoint that breaks the game before each player orders set be processed during the "Playing" state
	// Each player's order set will be processed at once, so the breakpoint controls the process based on
	// players, not on orders.
	EventDebugBreakpoint_StopByOrder EventDebugBreakpoint_Breakpoint = 0
	// Breakpoint that breaks the game before each player turn be processed during the "Playing" state
	EventDebugBreakpoint_StopByTurn EventDebugBreakpoint_Breakpoint = 1
)

var EventDebugBreakpoint_Breakpoint_name = map[int32]string{
	0: "StopByOrder",
	1: "StopByTurn",
}

var EventDebugBreakpoint_Breakpoint_value = map[string]int32{
	"StopByOrder": 0,
	"StopByTurn":  1,
}

func (x EventDebugBreakpoint_Breakpoint) String() string {
	return proto.EnumName(EventDebugBreakpoint_Breakpoint_name, int32(x))
}

func (EventDebugBreakpoint_Breakpoint) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_45f9368d1de3f31c, []int{5, 0}
}

// Brings the game snapshot and the event in a specialised format.
type GameEvent struct {
	// Game snapshot after the event has happened.
	GameSnapshot *GameSnapshot `protobuf:"bytes,1,opt,name=game_snapshot,json=gameSnapshot,proto3" json:"game_snapshot,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*GameEvent_NewPlayer
	//	*GameEvent_LostPlayer
	//	*GameEvent_StateChange
	//	*GameEvent_GameOver
	//	*GameEvent_Breakpoint
	//	*GameEvent_DebugReleased
	Event                isGameEvent_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GameEvent) Reset()         { *m = GameEvent{} }
func (m *GameEvent) String() string { return proto.CompactTextString(m) }
func (*GameEvent) ProtoMessage()    {}
func (*GameEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_45f9368d1de3f31c, []int{0}
}

func (m *GameEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameEvent.Unmarshal(m, b)
}
func (m *GameEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameEvent.Marshal(b, m, deterministic)
}
func (m *GameEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameEvent.Merge(m, src)
}
func (m *GameEvent) XXX_Size() int {
	return xxx_messageInfo_GameEvent.Size(m)
}
func (m *GameEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GameEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GameEvent proto.InternalMessageInfo

func (m *GameEvent) GetGameSnapshot() *GameSnapshot {
	if m != nil {
		return m.GameSnapshot
	}
	return nil
}

type isGameEvent_Event interface {
	isGameEvent_Event()
}

type GameEvent_NewPlayer struct {
	NewPlayer *EventNewPlayer `protobuf:"bytes,2,opt,name=new_player,json=newPlayer,proto3,oneof"`
}

type GameEvent_LostPlayer struct {
	LostPlayer *EventLostPlayer `protobuf:"bytes,3,opt,name=lost_player,json=lostPlayer,proto3,oneof"`
}

type GameEvent_StateChange struct {
	StateChange *EventStateChange `protobuf:"bytes,4,opt,name=state_change,json=stateChange,proto3,oneof"`
}

type GameEvent_GameOver struct {
	GameOver *EventGameOver `protobuf:"bytes,5,opt,name=game_over,json=gameOver,proto3,oneof"`
}

type GameEvent_Breakpoint struct {
	Breakpoint *EventDebugBreakpoint `protobuf:"bytes,6,opt,name=breakpoint,proto3,oneof"`
}

type GameEvent_DebugReleased struct {
	DebugReleased *EventDebugReleased `protobuf:"bytes,7,opt,name=debug_released,json=debugReleased,proto3,oneof"`
}

func (*GameEvent_NewPlayer) isGameEvent_Event() {}

func (*GameEvent_LostPlayer) isGameEvent_Event() {}

func (*GameEvent_StateChange) isGameEvent_Event() {}

func (*GameEvent_GameOver) isGameEvent_Event() {}

func (*GameEvent_Breakpoint) isGameEvent_Event() {}

func (*GameEvent_DebugReleased) isGameEvent_Event() {}

func (m *GameEvent) GetEvent() isGameEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *GameEvent) GetNewPlayer() *EventNewPlayer {
	if x, ok := m.GetEvent().(*GameEvent_NewPlayer); ok {
		return x.NewPlayer
	}
	return nil
}

func (m *GameEvent) GetLostPlayer() *EventLostPlayer {
	if x, ok := m.GetEvent().(*GameEvent_LostPlayer); ok {
		return x.LostPlayer
	}
	return nil
}

func (m *GameEvent) GetStateChange() *EventStateChange {
	if x, ok := m.GetEvent().(*GameEvent_StateChange); ok {
		return x.StateChange
	}
	return nil
}

func (m *GameEvent) GetGameOver() *EventGameOver {
	if x, ok := m.GetEvent().(*GameEvent_GameOver); ok {
		return x.GameOver
	}
	return nil
}

func (m *GameEvent) GetBreakpoint() *EventDebugBreakpoint {
	if x, ok := m.GetEvent().(*GameEvent_Breakpoint); ok {
		return x.Breakpoint
	}
	return nil
}

func (m *GameEvent) GetDebugReleased() *EventDebugReleased {
	if x, ok := m.GetEvent().(*GameEvent_DebugReleased); ok {
		return x.DebugReleased
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GameEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GameEvent_NewPlayer)(nil),
		(*GameEvent_LostPlayer)(nil),
		(*GameEvent_StateChange)(nil),
		(*GameEvent_GameOver)(nil),
		(*GameEvent_Breakpoint)(nil),
		(*GameEvent_DebugReleased)(nil),
	}
}

// Represents the event of having a new player connected to the game.
type EventNewPlayer struct {
	// Player that has connected to the game.
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventNewPlayer) Reset()         { *m = EventNewPlayer{} }
func (m *EventNewPlayer) String() string { return proto.CompactTextString(m) }
func (*EventNewPlayer) ProtoMessage()    {}
func (*EventNewPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_45f9368d1de3f31c, []int{1}
}

func (m *EventNewPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventNewPlayer.Unmarshal(m, b)
}
func (m *EventNewPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventNewPlayer.Marshal(b, m, deterministic)
}
func (m *EventNewPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventNewPlayer.Merge(m, src)
}
func (m *EventNewPlayer) XXX_Size() int {
	return xxx_messageInfo_EventNewPlayer.Size(m)
}
func (m *EventNewPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_EventNewPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_EventNewPlayer proto.InternalMessageInfo

func (m *EventNewPlayer) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

// Represents the event of having a player disconnected from the game.
type EventLostPlayer struct {
	// Player that has disconnected from the game.
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventLostPlayer) Reset()         { *m = EventLostPlayer{} }
func (m *EventLostPlayer) String() string { return proto.CompactTextString(m) }
func (*EventLostPlayer) ProtoMessage()    {}
func (*EventLostPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_45f9368d1de3f31c, []int{2}
}

func (m *EventLostPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventLostPlayer.Unmarshal(m, b)
}
func (m *EventLostPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventLostPlayer.Marshal(b, m, deterministic)
}
func (m *EventLostPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLostPlayer.Merge(m, src)
}
func (m *EventLostPlayer) XXX_Size() int {
	return xxx_messageInfo_EventLostPlayer.Size(m)
}
func (m *EventLostPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLostPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_EventLostPlayer proto.InternalMessageInfo

func (m *EventLostPlayer) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

// Represents the event of having the game state changed (e.g. from Waiting to GetReady).
type EventStateChange struct {
	// State of the game before the event.
	PreviousState GameSnapshot_State `protobuf:"varint,1,opt,name=previous_state,json=previousState,proto3,enum=lugo.GameSnapshot_State" json:"previous_state,omitempty"`
	// State of the game after the event.
	NewState             GameSnapshot_State `protobuf:"varint,2,opt,name=new_state,json=newState,proto3,enum=lugo.GameSnapshot_State" json:"new_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EventStateChange) Reset()         { *m = EventStateChange{} }
func (m *EventStateChange) String() string { return proto.CompactTextString(m) }
func (*EventStateChange) ProtoMessage()    {}
func (*EventStateChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_45f9368d1de3f31c, []int{3}
}

func (m *EventStateChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventStateChange.Unmarshal(m, b)
}
func (m *EventStateChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventStateChange.Marshal(b, m, deterministic)
}
func (m *EventStateChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventStateChange.Merge(m, src)
}
func (m *EventStateChange) XXX_Size() int {
	return xxx_messageInfo_EventStateChange.Size(m)
}
func (m *EventStateChange) XXX_DiscardUnknown() {
	xxx_messageInfo_EventStateChange.DiscardUnknown(m)
}

var xxx_messageInfo_EventStateChange proto.InternalMessageInfo

func (m *EventStateChange) GetPreviousState() GameSnapshot_State {
	if m != nil {
		return m.PreviousState
	}
	return GameSnapshot_WAITING
}

func (m *EventStateChange) GetNewState() GameSnapshot_State {
	if m != nil {
		return m.NewState
	}
	return GameSnapshot_WAITING
}

// Represents the event of having the game ended.
type EventGameOver struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventGameOver) Reset()         { *m = EventGameOver{} }
func (m *EventGameOver) String() string { return proto.CompactTextString(m) }
func (*EventGameOver) ProtoMessage()    {}
func (*EventGameOver) Descriptor() ([]byte, []int) {
	return fileDescriptor_45f9368d1de3f31c, []int{4}
}

func (m *EventGameOver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventGameOver.Unmarshal(m, b)
}
func (m *EventGameOver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventGameOver.Marshal(b, m, deterministic)
}
func (m *EventGameOver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventGameOver.Merge(m, src)
}
func (m *EventGameOver) XXX_Size() int {
	return xxx_messageInfo_EventGameOver.Size(m)
}
func (m *EventGameOver) XXX_DiscardUnknown() {
	xxx_messageInfo_EventGameOver.DiscardUnknown(m)
}

var xxx_messageInfo_EventGameOver proto.InternalMessageInfo

// (only available dev mode) Represents the event of having a breakpoint reached.
type EventDebugBreakpoint struct {
	// Type of the breakpoint reached.
	Breakpoint           EventDebugBreakpoint_Breakpoint `protobuf:"varint,1,opt,name=breakpoint,proto3,enum=lugo.EventDebugBreakpoint_Breakpoint" json:"breakpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *EventDebugBreakpoint) Reset()         { *m = EventDebugBreakpoint{} }
func (m *EventDebugBreakpoint) String() string { return proto.CompactTextString(m) }
func (*EventDebugBreakpoint) ProtoMessage()    {}
func (*EventDebugBreakpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_45f9368d1de3f31c, []int{5}
}

func (m *EventDebugBreakpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDebugBreakpoint.Unmarshal(m, b)
}
func (m *EventDebugBreakpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDebugBreakpoint.Marshal(b, m, deterministic)
}
func (m *EventDebugBreakpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDebugBreakpoint.Merge(m, src)
}
func (m *EventDebugBreakpoint) XXX_Size() int {
	return xxx_messageInfo_EventDebugBreakpoint.Size(m)
}
func (m *EventDebugBreakpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDebugBreakpoint.DiscardUnknown(m)
}

var xxx_messageInfo_EventDebugBreakpoint proto.InternalMessageInfo

func (m *EventDebugBreakpoint) GetBreakpoint() EventDebugBreakpoint_Breakpoint {
	if m != nil {
		return m.Breakpoint
	}
	return EventDebugBreakpoint_StopByOrder
}

// (only available dev mode) Represents the event of having a breakpoint released.
type EventDebugReleased struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventDebugReleased) Reset()         { *m = EventDebugReleased{} }
func (m *EventDebugReleased) String() string { return proto.CompactTextString(m) }
func (*EventDebugReleased) ProtoMessage()    {}
func (*EventDebugReleased) Descriptor() ([]byte, []int) {
	return fileDescriptor_45f9368d1de3f31c, []int{6}
}

func (m *EventDebugReleased) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDebugReleased.Unmarshal(m, b)
}
func (m *EventDebugReleased) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDebugReleased.Marshal(b, m, deterministic)
}
func (m *EventDebugReleased) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDebugReleased.Merge(m, src)
}
func (m *EventDebugReleased) XXX_Size() int {
	return xxx_messageInfo_EventDebugReleased.Size(m)
}
func (m *EventDebugReleased) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDebugReleased.DiscardUnknown(m)
}

var xxx_messageInfo_EventDebugReleased proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("lugo.EventDebugBreakpoint_Breakpoint", EventDebugBreakpoint_Breakpoint_name, EventDebugBreakpoint_Breakpoint_value)
	proto.RegisterType((*GameEvent)(nil), "lugo.GameEvent")
	proto.RegisterType((*EventNewPlayer)(nil), "lugo.EventNewPlayer")
	proto.RegisterType((*EventLostPlayer)(nil), "lugo.EventLostPlayer")
	proto.RegisterType((*EventStateChange)(nil), "lugo.EventStateChange")
	proto.RegisterType((*EventGameOver)(nil), "lugo.EventGameOver")
	proto.RegisterType((*EventDebugBreakpoint)(nil), "lugo.EventDebugBreakpoint")
	proto.RegisterType((*EventDebugReleased)(nil), "lugo.EventDebugReleased")
}

func init() {
	proto.RegisterFile("broadcast.proto", fileDescriptor_45f9368d1de3f31c)
}

var fileDescriptor_45f9368d1de3f31c = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0x9b, 0xfb, 0xd1, 0x5e, 0xa7, 0x3f, 0x59, 0xeb, 0x11, 0xea, 0x8b, 0x04, 0x05, 0x5f,
	0xcc, 0x49, 0xf5, 0x3c, 0x41, 0x41, 0xae, 0x5a, 0xec, 0x83, 0x58, 0x49, 0x7d, 0x0f, 0x9b, 0xcb,
	0x98, 0x3b, 0x4c, 0xb3, 0x61, 0x77, 0x93, 0xd2, 0x7f, 0x41, 0xfc, 0x63, 0xfc, 0x13, 0x25, 0xb3,
	0x49, 0x9b, 0x56, 0x45, 0xdf, 0x76, 0xf6, 0xfb, 0xfd, 0x4c, 0x32, 0x33, 0x3b, 0x30, 0x08, 0xa4,
	0xe0, 0xe1, 0x0d, 0x57, 0xda, 0x4d, 0xa5, 0xd0, 0x82, 0x9d, 0xc4, 0x59, 0x24, 0xc6, 0x5d, 0x85,
	0x32, 0x47, 0x69, 0xee, 0xc6, 0x0f, 0x22, 0x21, 0xa2, 0x18, 0x2f, 0x28, 0x0a, 0xb2, 0xaf, 0x17,
	0xb8, 0x4a, 0xf5, 0xc6, 0x88, 0xce, 0xcf, 0x63, 0x68, 0x7f, 0xe0, 0x2b, 0x9c, 0xe5, 0x98, 0x68,
	0x76, 0x05, 0xbd, 0x88, 0xaf, 0xd0, 0x57, 0x09, 0x4f, 0xd5, 0xad, 0xd0, 0xb6, 0xf5, 0xd0, 0x7a,
	0xd2, 0x99, 0x30, 0xb7, 0x48, 0xeb, 0x16, 0xbe, 0x65, 0xa9, 0x78, 0xdd, 0xa8, 0x16, 0xb1, 0x4b,
	0x80, 0x04, 0xd7, 0x7e, 0x1a, 0xf3, 0x0d, 0x4a, 0xfb, 0x88, 0xa8, 0x91, 0xa1, 0x28, 0xf3, 0x27,
	0x5c, 0x7f, 0x26, 0x6d, 0xde, 0xf0, 0xda, 0x49, 0x15, 0xb0, 0x57, 0xd0, 0x89, 0x85, 0xd2, 0x15,
	0x77, 0x4c, 0xdc, 0xfd, 0x1a, 0xf7, 0x51, 0x28, 0xbd, 0x05, 0x21, 0xde, 0x46, 0xec, 0x35, 0x74,
	0x95, 0xe6, 0x1a, 0xfd, 0x9b, 0x5b, 0x9e, 0x44, 0x68, 0x9f, 0x10, 0x7a, 0x5e, 0x43, 0x97, 0x85,
	0xfc, 0x8e, 0xd4, 0x79, 0xc3, 0xeb, 0xa8, 0x5d, 0xc8, 0x26, 0xd0, 0xa6, 0x32, 0x45, 0x8e, 0xd2,
	0x3e, 0x25, 0xf2, 0x5e, 0x8d, 0x2c, 0xea, 0x5c, 0xe4, 0xf4, 0xc9, 0xb3, 0xa8, 0x3c, 0xb3, 0x37,
	0x00, 0x81, 0x44, 0xfe, 0x2d, 0x15, 0x77, 0x89, 0xb6, 0x9b, 0x04, 0x8d, 0x6b, 0xd0, 0x7b, 0x0c,
	0xb2, 0x68, 0xba, 0x75, 0x14, 0xbf, 0xbb, 0xf3, 0xb3, 0x6b, 0xe8, 0x87, 0x85, 0xc1, 0x97, 0x18,
	0x23, 0x57, 0x18, 0xda, 0x2d, 0xca, 0x60, 0x1f, 0x66, 0xf0, 0x4a, 0x7d, 0xde, 0xf0, 0x7a, 0x61,
	0xfd, 0x62, 0xda, 0x82, 0x53, 0x2c, 0x6c, 0xce, 0x4b, 0xe8, 0xef, 0xf7, 0x94, 0x3d, 0x82, 0x66,
	0xd9, 0x41, 0x33, 0xaf, 0xae, 0xc9, 0x6a, 0x54, 0xaf, 0xd4, 0x9c, 0x2b, 0x18, 0x1c, 0xf4, 0xf4,
	0x3f, 0xc1, 0xef, 0x16, 0x0c, 0x0f, 0x5b, 0xca, 0xde, 0x42, 0x3f, 0x95, 0x98, 0xdf, 0x89, 0x4c,
	0xf9, 0xd4, 0x5b, 0x4a, 0xd1, 0xaf, 0x2a, 0xaa, 0xbf, 0x15, 0x97, 0x38, 0xaf, 0x57, 0xf9, 0x29,
	0x64, 0x97, 0x50, 0x3c, 0x84, 0x92, 0x3d, 0xfa, 0x07, 0x7b, 0x96, 0xe0, 0x9a, 0x4e, 0xce, 0x00,
	0x7a, 0x7b, 0x43, 0x72, 0x7e, 0x58, 0x30, 0xfa, 0xd3, 0x04, 0xd8, 0x6c, 0x6f, 0x62, 0xe6, 0xef,
	0x1e, 0xff, 0x7d, 0x62, 0xee, 0xee, 0x58, 0x1f, 0x9d, 0xf3, 0x14, 0xa0, 0x96, 0x74, 0x00, 0x9d,
	0xa5, 0x16, 0xe9, 0x74, 0xb3, 0x90, 0x21, 0xca, 0x61, 0x83, 0xf5, 0x01, 0xcc, 0xc5, 0x97, 0x4c,
	0x26, 0x43, 0xcb, 0x19, 0x01, 0xfb, 0x7d, 0x9a, 0x93, 0x6b, 0x68, 0x4f, 0xab, 0x55, 0x65, 0x2f,
	0xa0, 0xb5, 0x48, 0xcc, 0xc2, 0x9d, 0xbb, 0x66, 0x39, 0xdd, 0x6a, 0x39, 0xdd, 0x59, 0xb1, 0x9c,
	0xe3, 0xc1, 0xae, 0x13, 0x64, 0x7c, 0x66, 0x05, 0x4d, 0xb2, 0x3c, 0xff, 0x15, 0x00, 0x00, 0xff,
	0xff, 0xf2, 0x92, 0x62, 0xc7, 0xf4, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BroadcastClient is the client API for Broadcast service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BroadcastClient interface {
	// Keep an open stream that publish all important events in the match.
	OnEvent(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Broadcast_OnEventClient, error)
}

type broadcastClient struct {
	cc grpc.ClientConnInterface
}

func NewBroadcastClient(cc grpc.ClientConnInterface) BroadcastClient {
	return &broadcastClient{cc}
}

func (c *broadcastClient) OnEvent(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Broadcast_OnEventClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Broadcast_serviceDesc.Streams[0], "/lugo.Broadcast/OnEvent", opts...)
	if err != nil {
		return nil, err
	}
	x := &broadcastOnEventClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Broadcast_OnEventClient interface {
	Recv() (*GameEvent, error)
	grpc.ClientStream
}

type broadcastOnEventClient struct {
	grpc.ClientStream
}

func (x *broadcastOnEventClient) Recv() (*GameEvent, error) {
	m := new(GameEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BroadcastServer is the server API for Broadcast service.
type BroadcastServer interface {
	// Keep an open stream that publish all important events in the match.
	OnEvent(*empty.Empty, Broadcast_OnEventServer) error
}

// UnimplementedBroadcastServer can be embedded to have forward compatible implementations.
type UnimplementedBroadcastServer struct {
}

func (*UnimplementedBroadcastServer) OnEvent(req *empty.Empty, srv Broadcast_OnEventServer) error {
	return status.Errorf(codes.Unimplemented, "method OnEvent not implemented")
}

func RegisterBroadcastServer(s *grpc.Server, srv BroadcastServer) {
	s.RegisterService(&_Broadcast_serviceDesc, srv)
}

func _Broadcast_OnEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BroadcastServer).OnEvent(m, &broadcastOnEventServer{stream})
}

type Broadcast_OnEventServer interface {
	Send(*GameEvent) error
	grpc.ServerStream
}

type broadcastOnEventServer struct {
	grpc.ServerStream
}

func (x *broadcastOnEventServer) Send(m *GameEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _Broadcast_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lugo.Broadcast",
	HandlerType: (*BroadcastServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnEvent",
			Handler:       _Broadcast_OnEvent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "broadcast.proto",
}
