// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/broadcast.proto

package lugo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventDebugBreakpoint_Breakpoint int32

const (
	EventDebugBreakpoint_StopByOrder EventDebugBreakpoint_Breakpoint = 0
	EventDebugBreakpoint_StopByTurn  EventDebugBreakpoint_Breakpoint = 1
)

var EventDebugBreakpoint_Breakpoint_name = map[int32]string{
	0: "StopByOrder",
	1: "StopByTurn",
}

var EventDebugBreakpoint_Breakpoint_value = map[string]int32{
	"StopByOrder": 0,
	"StopByTurn":  1,
}

func (x EventDebugBreakpoint_Breakpoint) String() string {
	return proto.EnumName(EventDebugBreakpoint_Breakpoint_name, int32(x))
}

func (EventDebugBreakpoint_Breakpoint) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4afaf556da395531, []int{5, 0}
}

type GameEvent struct {
	GameSnapshot *GameSnapshot `protobuf:"bytes,1,opt,name=game_snapshot,json=gameSnapshot,proto3" json:"game_snapshot,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*GameEvent_NewPlayer
	//	*GameEvent_LostPlayer
	//	*GameEvent_StateChange
	//	*GameEvent_GameOver
	//	*GameEvent_Breakpoint
	//	*GameEvent_DebugReleased
	Event                isGameEvent_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GameEvent) Reset()         { *m = GameEvent{} }
func (m *GameEvent) String() string { return proto.CompactTextString(m) }
func (*GameEvent) ProtoMessage()    {}
func (*GameEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_4afaf556da395531, []int{0}
}

func (m *GameEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameEvent.Unmarshal(m, b)
}
func (m *GameEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameEvent.Marshal(b, m, deterministic)
}
func (m *GameEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameEvent.Merge(m, src)
}
func (m *GameEvent) XXX_Size() int {
	return xxx_messageInfo_GameEvent.Size(m)
}
func (m *GameEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GameEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GameEvent proto.InternalMessageInfo

func (m *GameEvent) GetGameSnapshot() *GameSnapshot {
	if m != nil {
		return m.GameSnapshot
	}
	return nil
}

type isGameEvent_Event interface {
	isGameEvent_Event()
}

type GameEvent_NewPlayer struct {
	NewPlayer *EventNewPlayer `protobuf:"bytes,2,opt,name=new_player,json=newPlayer,proto3,oneof"`
}

type GameEvent_LostPlayer struct {
	LostPlayer *EventLostPlayer `protobuf:"bytes,3,opt,name=lost_player,json=lostPlayer,proto3,oneof"`
}

type GameEvent_StateChange struct {
	StateChange *EventStateChange `protobuf:"bytes,4,opt,name=state_change,json=stateChange,proto3,oneof"`
}

type GameEvent_GameOver struct {
	GameOver *EventGameOver `protobuf:"bytes,5,opt,name=game_over,json=gameOver,proto3,oneof"`
}

type GameEvent_Breakpoint struct {
	Breakpoint *EventDebugBreakpoint `protobuf:"bytes,6,opt,name=breakpoint,proto3,oneof"`
}

type GameEvent_DebugReleased struct {
	DebugReleased *EventDebugReleased `protobuf:"bytes,7,opt,name=debug_released,json=debugReleased,proto3,oneof"`
}

func (*GameEvent_NewPlayer) isGameEvent_Event() {}

func (*GameEvent_LostPlayer) isGameEvent_Event() {}

func (*GameEvent_StateChange) isGameEvent_Event() {}

func (*GameEvent_GameOver) isGameEvent_Event() {}

func (*GameEvent_Breakpoint) isGameEvent_Event() {}

func (*GameEvent_DebugReleased) isGameEvent_Event() {}

func (m *GameEvent) GetEvent() isGameEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *GameEvent) GetNewPlayer() *EventNewPlayer {
	if x, ok := m.GetEvent().(*GameEvent_NewPlayer); ok {
		return x.NewPlayer
	}
	return nil
}

func (m *GameEvent) GetLostPlayer() *EventLostPlayer {
	if x, ok := m.GetEvent().(*GameEvent_LostPlayer); ok {
		return x.LostPlayer
	}
	return nil
}

func (m *GameEvent) GetStateChange() *EventStateChange {
	if x, ok := m.GetEvent().(*GameEvent_StateChange); ok {
		return x.StateChange
	}
	return nil
}

func (m *GameEvent) GetGameOver() *EventGameOver {
	if x, ok := m.GetEvent().(*GameEvent_GameOver); ok {
		return x.GameOver
	}
	return nil
}

func (m *GameEvent) GetBreakpoint() *EventDebugBreakpoint {
	if x, ok := m.GetEvent().(*GameEvent_Breakpoint); ok {
		return x.Breakpoint
	}
	return nil
}

func (m *GameEvent) GetDebugReleased() *EventDebugReleased {
	if x, ok := m.GetEvent().(*GameEvent_DebugReleased); ok {
		return x.DebugReleased
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GameEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GameEvent_NewPlayer)(nil),
		(*GameEvent_LostPlayer)(nil),
		(*GameEvent_StateChange)(nil),
		(*GameEvent_GameOver)(nil),
		(*GameEvent_Breakpoint)(nil),
		(*GameEvent_DebugReleased)(nil),
	}
}

type EventNewPlayer struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventNewPlayer) Reset()         { *m = EventNewPlayer{} }
func (m *EventNewPlayer) String() string { return proto.CompactTextString(m) }
func (*EventNewPlayer) ProtoMessage()    {}
func (*EventNewPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_4afaf556da395531, []int{1}
}

func (m *EventNewPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventNewPlayer.Unmarshal(m, b)
}
func (m *EventNewPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventNewPlayer.Marshal(b, m, deterministic)
}
func (m *EventNewPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventNewPlayer.Merge(m, src)
}
func (m *EventNewPlayer) XXX_Size() int {
	return xxx_messageInfo_EventNewPlayer.Size(m)
}
func (m *EventNewPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_EventNewPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_EventNewPlayer proto.InternalMessageInfo

func (m *EventNewPlayer) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type EventLostPlayer struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventLostPlayer) Reset()         { *m = EventLostPlayer{} }
func (m *EventLostPlayer) String() string { return proto.CompactTextString(m) }
func (*EventLostPlayer) ProtoMessage()    {}
func (*EventLostPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_4afaf556da395531, []int{2}
}

func (m *EventLostPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventLostPlayer.Unmarshal(m, b)
}
func (m *EventLostPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventLostPlayer.Marshal(b, m, deterministic)
}
func (m *EventLostPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLostPlayer.Merge(m, src)
}
func (m *EventLostPlayer) XXX_Size() int {
	return xxx_messageInfo_EventLostPlayer.Size(m)
}
func (m *EventLostPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLostPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_EventLostPlayer proto.InternalMessageInfo

func (m *EventLostPlayer) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type EventStateChange struct {
	PreviousState        GameSnapshot_State `protobuf:"varint,1,opt,name=previous_state,json=previousState,proto3,enum=lugo.GameSnapshot_State" json:"previous_state,omitempty"`
	NewState             GameSnapshot_State `protobuf:"varint,2,opt,name=new_state,json=newState,proto3,enum=lugo.GameSnapshot_State" json:"new_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EventStateChange) Reset()         { *m = EventStateChange{} }
func (m *EventStateChange) String() string { return proto.CompactTextString(m) }
func (*EventStateChange) ProtoMessage()    {}
func (*EventStateChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_4afaf556da395531, []int{3}
}

func (m *EventStateChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventStateChange.Unmarshal(m, b)
}
func (m *EventStateChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventStateChange.Marshal(b, m, deterministic)
}
func (m *EventStateChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventStateChange.Merge(m, src)
}
func (m *EventStateChange) XXX_Size() int {
	return xxx_messageInfo_EventStateChange.Size(m)
}
func (m *EventStateChange) XXX_DiscardUnknown() {
	xxx_messageInfo_EventStateChange.DiscardUnknown(m)
}

var xxx_messageInfo_EventStateChange proto.InternalMessageInfo

func (m *EventStateChange) GetPreviousState() GameSnapshot_State {
	if m != nil {
		return m.PreviousState
	}
	return GameSnapshot_WAITING
}

func (m *EventStateChange) GetNewState() GameSnapshot_State {
	if m != nil {
		return m.NewState
	}
	return GameSnapshot_WAITING
}

type EventGameOver struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventGameOver) Reset()         { *m = EventGameOver{} }
func (m *EventGameOver) String() string { return proto.CompactTextString(m) }
func (*EventGameOver) ProtoMessage()    {}
func (*EventGameOver) Descriptor() ([]byte, []int) {
	return fileDescriptor_4afaf556da395531, []int{4}
}

func (m *EventGameOver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventGameOver.Unmarshal(m, b)
}
func (m *EventGameOver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventGameOver.Marshal(b, m, deterministic)
}
func (m *EventGameOver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventGameOver.Merge(m, src)
}
func (m *EventGameOver) XXX_Size() int {
	return xxx_messageInfo_EventGameOver.Size(m)
}
func (m *EventGameOver) XXX_DiscardUnknown() {
	xxx_messageInfo_EventGameOver.DiscardUnknown(m)
}

var xxx_messageInfo_EventGameOver proto.InternalMessageInfo

type EventDebugBreakpoint struct {
	Breakpoint           EventDebugBreakpoint_Breakpoint `protobuf:"varint,1,opt,name=breakpoint,proto3,enum=lugo.EventDebugBreakpoint_Breakpoint" json:"breakpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *EventDebugBreakpoint) Reset()         { *m = EventDebugBreakpoint{} }
func (m *EventDebugBreakpoint) String() string { return proto.CompactTextString(m) }
func (*EventDebugBreakpoint) ProtoMessage()    {}
func (*EventDebugBreakpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_4afaf556da395531, []int{5}
}

func (m *EventDebugBreakpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDebugBreakpoint.Unmarshal(m, b)
}
func (m *EventDebugBreakpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDebugBreakpoint.Marshal(b, m, deterministic)
}
func (m *EventDebugBreakpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDebugBreakpoint.Merge(m, src)
}
func (m *EventDebugBreakpoint) XXX_Size() int {
	return xxx_messageInfo_EventDebugBreakpoint.Size(m)
}
func (m *EventDebugBreakpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDebugBreakpoint.DiscardUnknown(m)
}

var xxx_messageInfo_EventDebugBreakpoint proto.InternalMessageInfo

func (m *EventDebugBreakpoint) GetBreakpoint() EventDebugBreakpoint_Breakpoint {
	if m != nil {
		return m.Breakpoint
	}
	return EventDebugBreakpoint_StopByOrder
}

type EventDebugReleased struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventDebugReleased) Reset()         { *m = EventDebugReleased{} }
func (m *EventDebugReleased) String() string { return proto.CompactTextString(m) }
func (*EventDebugReleased) ProtoMessage()    {}
func (*EventDebugReleased) Descriptor() ([]byte, []int) {
	return fileDescriptor_4afaf556da395531, []int{6}
}

func (m *EventDebugReleased) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDebugReleased.Unmarshal(m, b)
}
func (m *EventDebugReleased) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDebugReleased.Marshal(b, m, deterministic)
}
func (m *EventDebugReleased) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDebugReleased.Merge(m, src)
}
func (m *EventDebugReleased) XXX_Size() int {
	return xxx_messageInfo_EventDebugReleased.Size(m)
}
func (m *EventDebugReleased) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDebugReleased.DiscardUnknown(m)
}

var xxx_messageInfo_EventDebugReleased proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("lugo.EventDebugBreakpoint_Breakpoint", EventDebugBreakpoint_Breakpoint_name, EventDebugBreakpoint_Breakpoint_value)
	proto.RegisterType((*GameEvent)(nil), "lugo.GameEvent")
	proto.RegisterType((*EventNewPlayer)(nil), "lugo.EventNewPlayer")
	proto.RegisterType((*EventLostPlayer)(nil), "lugo.EventLostPlayer")
	proto.RegisterType((*EventStateChange)(nil), "lugo.EventStateChange")
	proto.RegisterType((*EventGameOver)(nil), "lugo.EventGameOver")
	proto.RegisterType((*EventDebugBreakpoint)(nil), "lugo.EventDebugBreakpoint")
	proto.RegisterType((*EventDebugReleased)(nil), "lugo.EventDebugReleased")
}

func init() {
	proto.RegisterFile("proto/broadcast.proto", fileDescriptor_4afaf556da395531)
}

var fileDescriptor_4afaf556da395531 = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xdd, 0x6e, 0xd3, 0x40,
	0x10, 0x85, 0xe3, 0xfe, 0x24, 0xcd, 0xe4, 0x57, 0x4b, 0x5a, 0x59, 0xe1, 0x06, 0x59, 0x20, 0x71,
	0x83, 0x83, 0x02, 0xa5, 0x48, 0x20, 0xa1, 0x06, 0x22, 0x72, 0x81, 0x08, 0x72, 0xb8, 0x8f, 0xd6,
	0xf5, 0xe0, 0x56, 0x38, 0x5e, 0x6b, 0x77, 0xed, 0x28, 0xaf, 0x80, 0x78, 0x18, 0x1e, 0x11, 0x79,
	0xd6, 0x4e, 0x9c, 0x00, 0xa2, 0x77, 0x3b, 0x3e, 0xe7, 0x1b, 0x7b, 0xe7, 0x78, 0xe0, 0x3c, 0x91,
	0x42, 0x8b, 0x91, 0x2f, 0x05, 0x0f, 0x6e, 0xb8, 0xd2, 0x2e, 0xd5, 0xec, 0x24, 0x4a, 0x43, 0x31,
	0x64, 0x46, 0x54, 0x28, 0x33, 0x94, 0x46, 0x19, 0x3e, 0x0c, 0x85, 0x08, 0x23, 0x1c, 0x51, 0xe5,
	0xa7, 0xdf, 0x46, 0xb8, 0x4a, 0xf4, 0xc6, 0x88, 0xce, 0xaf, 0x63, 0x68, 0x7e, 0xe4, 0x2b, 0x9c,
	0x66, 0x18, 0x6b, 0x76, 0x05, 0x9d, 0x90, 0xaf, 0x70, 0xa9, 0x62, 0x9e, 0xa8, 0x5b, 0xa1, 0x6d,
	0xeb, 0x91, 0xf5, 0xb4, 0x35, 0x66, 0x6e, 0xde, 0xdc, 0xcd, 0x7d, 0x8b, 0x42, 0xf1, 0xda, 0x61,
	0xa5, 0x62, 0x97, 0x00, 0x31, 0xae, 0x97, 0x49, 0xc4, 0x37, 0x28, 0xed, 0x23, 0xa2, 0x06, 0x86,
	0xa2, 0xce, 0x9f, 0x71, 0xfd, 0x85, 0xb4, 0x59, 0xcd, 0x6b, 0xc6, 0x65, 0xc1, 0x5e, 0x43, 0x2b,
	0x12, 0x4a, 0x97, 0xdc, 0x31, 0x71, 0xe7, 0x15, 0xee, 0x93, 0x50, 0x7a, 0x0b, 0x42, 0xb4, 0xad,
	0xd8, 0x1b, 0x68, 0x2b, 0xcd, 0x35, 0x2e, 0x6f, 0x6e, 0x79, 0x1c, 0xa2, 0x7d, 0x42, 0xe8, 0x45,
	0x05, 0x5d, 0xe4, 0xf2, 0x7b, 0x52, 0x67, 0x35, 0xaf, 0xa5, 0x76, 0x25, 0x1b, 0x43, 0x93, 0xae,
	0x29, 0x32, 0x94, 0xf6, 0x29, 0x91, 0x0f, 0x2a, 0x64, 0x7e, 0xcf, 0x79, 0x46, 0xaf, 0x3c, 0x0b,
	0x8b, 0x33, 0x7b, 0x0b, 0xe0, 0x4b, 0xe4, 0xdf, 0x13, 0x71, 0x17, 0x6b, 0xbb, 0x4e, 0xd0, 0xb0,
	0x02, 0x7d, 0x40, 0x3f, 0x0d, 0x27, 0x5b, 0x47, 0xfe, 0xb9, 0x3b, 0x3f, 0xbb, 0x86, 0x6e, 0x90,
	0x1b, 0x96, 0x12, 0x23, 0xe4, 0x0a, 0x03, 0xbb, 0x41, 0x1d, 0xec, 0xc3, 0x0e, 0x5e, 0xa1, 0xcf,
	0x6a, 0x5e, 0x27, 0xa8, 0x3e, 0x98, 0x34, 0xe0, 0x14, 0x73, 0x9b, 0xf3, 0x0a, 0xba, 0xfb, 0x33,
	0x65, 0x8f, 0xa1, 0x5e, 0x4c, 0xd0, 0xe4, 0xd5, 0x36, 0x5d, 0x8d, 0xea, 0x15, 0x9a, 0x73, 0x05,
	0xbd, 0x83, 0x99, 0xde, 0x13, 0xfc, 0x61, 0x41, 0xff, 0x70, 0xa4, 0xec, 0x1d, 0x74, 0x13, 0x89,
	0xd9, 0x9d, 0x48, 0xd5, 0x92, 0x66, 0x4b, 0x2d, 0xba, 0xe5, 0x8d, 0xaa, 0xff, 0x8a, 0x4b, 0x9c,
	0xd7, 0x29, 0xfd, 0x54, 0xb2, 0x4b, 0xc8, 0x7f, 0x84, 0x82, 0x3d, 0xfa, 0x0f, 0x7b, 0x16, 0xe3,
	0x9a, 0x4e, 0x4e, 0x0f, 0x3a, 0x7b, 0x21, 0x39, 0x3f, 0x2d, 0x18, 0xfc, 0x2d, 0x01, 0x36, 0xdd,
	0x4b, 0xcc, 0x7c, 0xdd, 0x93, 0x7f, 0x27, 0xe6, 0xee, 0x8e, 0xd5, 0xe8, 0x9c, 0x67, 0x00, 0x95,
	0xa6, 0x3d, 0x68, 0x2d, 0xb4, 0x48, 0x26, 0x9b, 0xb9, 0x0c, 0x50, 0xf6, 0x6b, 0xac, 0x0b, 0x60,
	0x1e, 0x7c, 0x4d, 0x65, 0xdc, 0xb7, 0x9c, 0x01, 0xb0, 0x3f, 0xd3, 0x1c, 0x5f, 0x43, 0x73, 0x52,
	0x2e, 0x2c, 0x7b, 0x09, 0x8d, 0x79, 0x6c, 0x16, 0xee, 0xc2, 0x35, 0xcb, 0xe9, 0x96, 0xcb, 0xe9,
	0x4e, 0xf3, 0xe5, 0x1c, 0xf6, 0x76, 0x93, 0x20, 0xe3, 0x73, 0xcb, 0xaf, 0x93, 0xe5, 0xc5, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xa8, 0xb8, 0x6a, 0x00, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BroadcastClient is the client API for Broadcast service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BroadcastClient interface {
	OnEvent(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Broadcast_OnEventClient, error)
}

type broadcastClient struct {
	cc grpc.ClientConnInterface
}

func NewBroadcastClient(cc grpc.ClientConnInterface) BroadcastClient {
	return &broadcastClient{cc}
}

func (c *broadcastClient) OnEvent(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Broadcast_OnEventClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Broadcast_serviceDesc.Streams[0], "/lugo.Broadcast/OnEvent", opts...)
	if err != nil {
		return nil, err
	}
	x := &broadcastOnEventClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Broadcast_OnEventClient interface {
	Recv() (*GameEvent, error)
	grpc.ClientStream
}

type broadcastOnEventClient struct {
	grpc.ClientStream
}

func (x *broadcastOnEventClient) Recv() (*GameEvent, error) {
	m := new(GameEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BroadcastServer is the server API for Broadcast service.
type BroadcastServer interface {
	OnEvent(*empty.Empty, Broadcast_OnEventServer) error
}

// UnimplementedBroadcastServer can be embedded to have forward compatible implementations.
type UnimplementedBroadcastServer struct {
}

func (*UnimplementedBroadcastServer) OnEvent(req *empty.Empty, srv Broadcast_OnEventServer) error {
	return status.Errorf(codes.Unimplemented, "method OnEvent not implemented")
}

func RegisterBroadcastServer(s *grpc.Server, srv BroadcastServer) {
	s.RegisterService(&_Broadcast_serviceDesc, srv)
}

func _Broadcast_OnEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BroadcastServer).OnEvent(m, &broadcastOnEventServer{stream})
}

type Broadcast_OnEventServer interface {
	Send(*GameEvent) error
	grpc.ServerStream
}

type broadcastOnEventServer struct {
	grpc.ServerStream
}

func (x *broadcastOnEventServer) Send(m *GameEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _Broadcast_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lugo.Broadcast",
	HandlerType: (*BroadcastServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnEvent",
			Handler:       _Broadcast_OnEvent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/broadcast.proto",
}
