// Code generated by protoc-gen-go. DO NOT EDIT.
// source: physics.proto

package lugo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
// Vector represent one direction on a cartesian plan
type Vector struct {
	// Coordinate X to define the vector direction.
	X float64 `protobuf:"fixed64,1,opt,name=X,proto3" json:"X,omitempty"`
	// Coordinate Y to define the vector direction.
	Y                    float64  `protobuf:"fixed64,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector) Reset()         { *m = Vector{} }
func (m *Vector) String() string { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()    {}
func (*Vector) Descriptor() ([]byte, []int) {
	return fileDescriptor_766fa8ef304a4bfc, []int{0}
}

func (m *Vector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector.Unmarshal(m, b)
}
func (m *Vector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector.Marshal(b, m, deterministic)
}
func (m *Vector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector.Merge(m, src)
}
func (m *Vector) XXX_Size() int {
	return xxx_messageInfo_Vector.Size(m)
}
func (m *Vector) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector.DiscardUnknown(m)
}

var xxx_messageInfo_Vector proto.InternalMessageInfo

func (m *Vector) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

//
// Point represents one position on the cartesian plan of the game field.
// The coordinates start at the left bottom corner from the top view .
type Point struct {
	// Distance from the Y axis to right.
	X int32 `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	// Distance from the X axis to up.
	Y                    int32    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_766fa8ef304a4bfc, []int{1}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

//
// Velocity is a tuple with the direction (a vector) an a speed (float) values.
// It defines the velocity of an object.
type Velocity struct {
	// Direction is a normalised vector that indicates the element direction
	Direction *Vector `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	// Speed of the element.
	Speed                float64  `protobuf:"fixed64,2,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Velocity) Reset()         { *m = Velocity{} }
func (m *Velocity) String() string { return proto.CompactTextString(m) }
func (*Velocity) ProtoMessage()    {}
func (*Velocity) Descriptor() ([]byte, []int) {
	return fileDescriptor_766fa8ef304a4bfc, []int{2}
}

func (m *Velocity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Velocity.Unmarshal(m, b)
}
func (m *Velocity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Velocity.Marshal(b, m, deterministic)
}
func (m *Velocity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Velocity.Merge(m, src)
}
func (m *Velocity) XXX_Size() int {
	return xxx_messageInfo_Velocity.Size(m)
}
func (m *Velocity) XXX_DiscardUnknown() {
	xxx_messageInfo_Velocity.DiscardUnknown(m)
}

var xxx_messageInfo_Velocity proto.InternalMessageInfo

func (m *Velocity) GetDirection() *Vector {
	if m != nil {
		return m.Direction
	}
	return nil
}

func (m *Velocity) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func init() {
	proto.RegisterType((*Vector)(nil), "lugo.Vector")
	proto.RegisterType((*Point)(nil), "lugo.Point")
	proto.RegisterType((*Velocity)(nil), "lugo.Velocity")
}

func init() {
	proto.RegisterFile("physics.proto", fileDescriptor_766fa8ef304a4bfc)
}

var fileDescriptor_766fa8ef304a4bfc = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xc8, 0xa8, 0x2c,
	0xce, 0x4c, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x29, 0x4d, 0xcf, 0x57,
	0x52, 0xe1, 0x62, 0x0b, 0x4b, 0x4d, 0x2e, 0xc9, 0x2f, 0x12, 0xe2, 0xe1, 0x62, 0x8c, 0x90, 0x60,
	0x54, 0x60, 0xd4, 0x60, 0x0c, 0x62, 0x8c, 0x00, 0xf1, 0x22, 0x25, 0x98, 0x20, 0xbc, 0x48, 0x25,
	0x65, 0x2e, 0xd6, 0x80, 0xfc, 0xcc, 0xbc, 0x12, 0x84, 0x22, 0x56, 0x14, 0x45, 0xac, 0x20, 0x45,
	0x3e, 0x5c, 0x1c, 0x61, 0xa9, 0x39, 0xf9, 0xc9, 0x99, 0x25, 0x95, 0x42, 0x5a, 0x5c, 0x9c, 0x29,
	0x99, 0x45, 0xa9, 0xc9, 0x25, 0x99, 0xf9, 0x79, 0x60, 0xf5, 0xdc, 0x46, 0x3c, 0x7a, 0x20, 0x0b,
	0xf5, 0x20, 0xb6, 0x05, 0x21, 0xa4, 0x85, 0x44, 0xb8, 0x58, 0x8b, 0x0b, 0x52, 0x53, 0x53, 0xa0,
	0xd6, 0x41, 0x38, 0x49, 0x6c, 0x60, 0x57, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xe7,
	0x53, 0x09, 0xb6, 0x00, 0x00, 0x00,
}
