// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/server.proto

package lugo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GameSnapshot_Phase int32

const (
	// The game is waiting for all players be connected. There is a configurable time limit to wait for players. After
	// this limit expires, the match is considered over.
	GameSnapshot_WAITING GameSnapshot_Phase = 0
	// The game resets the players position to start the match or to restart the match after a goal.
	GameSnapshot_GET_READY GameSnapshot_Phase = 1
	// The game is waiting for players orders. There is a configurable time window for this phase. After the time
	// limit expires, the server will ignore the missing orders and process the ones it got.
	// (when running on dev mode, the server may allow different behaviours)
	GameSnapshot_LISTENING GameSnapshot_Phase = 2
	// The game is executing the players' orders in the same sequence they were gotten.
	// If the ball is NOT been holden, its velocity will be processed first. Otherwise, it position will be updated
	// when the ball holder movement be processed.
	// If there is no movement orders from a player, but it has speed greater than 0, it will be processed after
	// all its orders are processed.
	// Each player orders will be processed in the same sequence they were included in the message (e.g. first move,
	// than kick)
	// The ball kick is processed immediately after the order (the ball position is updated as its new velocity
	// after the kick)
	GameSnapshot_PLAYING GameSnapshot_Phase = 3
	// The game may be over after any phase.
	// It can be over after Waiting if there is no players connected after the time limit for connections
	// It can be over after GetReady or Listening if there is no enough players (e.g. connection lost)
	// And it also can be over after Playing state if that was the last turn of the match.
	GameSnapshot_OVER GameSnapshot_Phase = 99
)

var GameSnapshot_Phase_name = map[int32]string{
	0:  "WAITING",
	1:  "GET_READY",
	2:  "LISTENING",
	3:  "PLAYING",
	99: "OVER",
}

var GameSnapshot_Phase_value = map[string]int32{
	"WAITING":   0,
	"GET_READY": 1,
	"LISTENING": 2,
	"PLAYING":   3,
	"OVER":      99,
}

func (x GameSnapshot_Phase) String() string {
	return proto.EnumName(GameSnapshot_Phase_name, int32(x))
}

func (GameSnapshot_Phase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{1, 0}
}

type Team_Side int32

const (
	// Team playing on the left side of field
	Team_HOME Team_Side = 0
	// Team playing on the right side of the field
	Team_AWAY Team_Side = 1
)

var Team_Side_name = map[int32]string{
	0: "HOME",
	1: "AWAY",
}

var Team_Side_value = map[string]int32{
	"HOME": 0,
	"AWAY": 1,
}

func (x Team_Side) String() string {
	return proto.EnumName(Team_Side_name, int32(x))
}

func (Team_Side) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{2, 0}
}

type OrderResponse_StatusCode int32

const (
	OrderResponse_SUCCESS        OrderResponse_StatusCode = 0
	OrderResponse_UNKNOWN_PLAYER OrderResponse_StatusCode = 1
	OrderResponse_NOT_LISTENING  OrderResponse_StatusCode = 2
	OrderResponse_WRONG_TURN     OrderResponse_StatusCode = 3
	OrderResponse_OTHER          OrderResponse_StatusCode = 99
)

var OrderResponse_StatusCode_name = map[int32]string{
	0:  "SUCCESS",
	1:  "UNKNOWN_PLAYER",
	2:  "NOT_LISTENING",
	3:  "WRONG_TURN",
	99: "OTHER",
}

var OrderResponse_StatusCode_value = map[string]int32{
	"SUCCESS":        0,
	"UNKNOWN_PLAYER": 1,
	"NOT_LISTENING":  2,
	"WRONG_TURN":     3,
	"OTHER":          99,
}

func (x OrderResponse_StatusCode) String() string {
	return proto.EnumName(OrderResponse_StatusCode_name, int32(x))
}

func (OrderResponse_StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{5, 0}
}

// JoinRequest define the player configuration to the game.
type JoinRequest struct {
	// Only used in official matches to guarantee that only one process will assume that player position (team and number).
	// The bot process will receive this token as an argument, and must send it to the server in this message.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Identifies the protocol version of the bot.
	ProtocolVersion string `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Identify the bot's team side (Team_Home or Team_Away)
	TeamSide Team_Side `protobuf:"varint,3,opt,name=team_side,json=teamSide,proto3,enum=proto.Team_Side" json:"team_side,omitempty"`
	// Player's number 1-11
	Number uint32 `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	// Position where the player must be set at "GetReady" state (at beginning of the match or after a goal)
	InitPosition         *Point   `protobuf:"bytes,5,opt,name=init_position,json=initPosition,proto3" json:"init_position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{0}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *JoinRequest) GetProtocolVersion() string {
	if m != nil {
		return m.ProtocolVersion
	}
	return ""
}

func (m *JoinRequest) GetTeamSide() Team_Side {
	if m != nil {
		return m.TeamSide
	}
	return Team_HOME
}

func (m *JoinRequest) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *JoinRequest) GetInitPosition() *Point {
	if m != nil {
		return m.InitPosition
	}
	return nil
}

// GameSnapshot stores all game elements data.
type GameSnapshot struct {
	// The game state defines which phase the game is. The phase determine what the server is doing, are going to do, or
	// what it is waiting for.
	State GameSnapshot_Phase `protobuf:"varint,1,opt,name=state,proto3,enum=proto.GameSnapshot_Phase" json:"state,omitempty"`
	// Turns counter. It starts from 1, but before the match starts, it may be zero.
	Turn uint32 `protobuf:"varint,2,opt,name=turn,proto3" json:"turn,omitempty"`
	// Store the home team elements.
	HomeTeam *Team `protobuf:"bytes,3,opt,name=home_team,json=homeTeam,proto3" json:"home_team,omitempty"`
	// Store the away team elements.
	AwayTeam *Team `protobuf:"bytes,4,opt,name=away_team,json=awayTeam,proto3" json:"away_team,omitempty"`
	// Store the ball element.
	Ball                 *Ball    `protobuf:"bytes,5,opt,name=ball,proto3" json:"ball,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameSnapshot) Reset()         { *m = GameSnapshot{} }
func (m *GameSnapshot) String() string { return proto.CompactTextString(m) }
func (*GameSnapshot) ProtoMessage()    {}
func (*GameSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{1}
}

func (m *GameSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameSnapshot.Unmarshal(m, b)
}
func (m *GameSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameSnapshot.Marshal(b, m, deterministic)
}
func (m *GameSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameSnapshot.Merge(m, src)
}
func (m *GameSnapshot) XXX_Size() int {
	return xxx_messageInfo_GameSnapshot.Size(m)
}
func (m *GameSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_GameSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_GameSnapshot proto.InternalMessageInfo

func (m *GameSnapshot) GetState() GameSnapshot_Phase {
	if m != nil {
		return m.State
	}
	return GameSnapshot_WAITING
}

func (m *GameSnapshot) GetTurn() uint32 {
	if m != nil {
		return m.Turn
	}
	return 0
}

func (m *GameSnapshot) GetHomeTeam() *Team {
	if m != nil {
		return m.HomeTeam
	}
	return nil
}

func (m *GameSnapshot) GetAwayTeam() *Team {
	if m != nil {
		return m.AwayTeam
	}
	return nil
}

func (m *GameSnapshot) GetBall() *Ball {
	if m != nil {
		return m.Ball
	}
	return nil
}

// Stores all team elements and data.
type Team struct {
	// List of player in the team
	Players []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	// Team name
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	// Team score in the present turn
	Score uint32 `protobuf:"varint,3,opt,name=Score,proto3" json:"Score,omitempty"`
	// Side which the team is playing on.
	Side                 Team_Side `protobuf:"varint,4,opt,name=side,proto3,enum=proto.Team_Side" json:"side,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{2}
}

func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (m *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(m, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Team) GetScore() uint32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Team) GetSide() Team_Side {
	if m != nil {
		return m.Side
	}
	return Team_HOME
}

// Stores all player attributes
type Player struct {
	// Number of this player in its team (1-11)
	Number uint32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	// Current player position
	Position *Point `protobuf:"bytes,2,opt,name=Position,proto3" json:"Position,omitempty"`
	// Current player velocity
	Velocity *Velocity `protobuf:"bytes,3,opt,name=velocity,proto3" json:"velocity,omitempty"`
	// Team side which its playing in (it's used to speed up some readings since the player element will be in a list
	// of players of a team)
	TeamSide Team_Side `protobuf:"varint,4,opt,name=team_side,json=teamSide,proto3,enum=proto.Team_Side" json:"team_side,omitempty"`
	// Default position when it's position is reset
	InitPosition         *Point   `protobuf:"bytes,5,opt,name=init_position,json=initPosition,proto3" json:"init_position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{3}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Player) GetPosition() *Point {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Player) GetVelocity() *Velocity {
	if m != nil {
		return m.Velocity
	}
	return nil
}

func (m *Player) GetTeamSide() Team_Side {
	if m != nil {
		return m.TeamSide
	}
	return Team_HOME
}

func (m *Player) GetInitPosition() *Point {
	if m != nil {
		return m.InitPosition
	}
	return nil
}

// Stores all ball attributes
type Ball struct {
	// Current position
	Position *Point `protobuf:"bytes,1,opt,name=Position,proto3" json:"Position,omitempty"`
	// Current velocity. It will be the exactly same velocity as the ball holder when a player is holding it.
	Velocity *Velocity `protobuf:"bytes,2,opt,name=velocity,proto3" json:"velocity,omitempty"`
	// Player that is currently holding the ball. Null if the ball is not holden.
	Holder               *Player  `protobuf:"bytes,3,opt,name=holder,proto3" json:"holder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ball) Reset()         { *m = Ball{} }
func (m *Ball) String() string { return proto.CompactTextString(m) }
func (*Ball) ProtoMessage()    {}
func (*Ball) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{4}
}

func (m *Ball) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ball.Unmarshal(m, b)
}
func (m *Ball) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ball.Marshal(b, m, deterministic)
}
func (m *Ball) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ball.Merge(m, src)
}
func (m *Ball) XXX_Size() int {
	return xxx_messageInfo_Ball.Size(m)
}
func (m *Ball) XXX_DiscardUnknown() {
	xxx_messageInfo_Ball.DiscardUnknown(m)
}

var xxx_messageInfo_Ball proto.InternalMessageInfo

func (m *Ball) GetPosition() *Point {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Ball) GetVelocity() *Velocity {
	if m != nil {
		return m.Velocity
	}
	return nil
}

func (m *Ball) GetHolder() *Player {
	if m != nil {
		return m.Holder
	}
	return nil
}

// Message sent to the player as a response after sending a order set to the the server.
type OrderResponse struct {
	// Define if the order will be correctly processed.
	Code OrderResponse_StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=proto.OrderResponse_StatusCode" json:"code,omitempty"`
	// String message used for debugging proposes.
	Details              string   `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{5}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetCode() OrderResponse_StatusCode {
	if m != nil {
		return m.Code
	}
	return OrderResponse_SUCCESS
}

func (m *OrderResponse) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

// Message containing the orders the player want to send to the server in that turn.
type OrderSet struct {
	// Turn which this order set should be processed at.
	Turn uint32 `protobuf:"varint,1,opt,name=turn,proto3" json:"turn,omitempty"`
	// List of orders in the expected order of execution
	Orders []*Order `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	// String message used for debugging proposes.
	DebugMessage         string   `protobuf:"bytes,3,opt,name=debug_message,json=debugMessage,proto3" json:"debug_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderSet) Reset()         { *m = OrderSet{} }
func (m *OrderSet) String() string { return proto.CompactTextString(m) }
func (*OrderSet) ProtoMessage()    {}
func (*OrderSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{6}
}

func (m *OrderSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderSet.Unmarshal(m, b)
}
func (m *OrderSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderSet.Marshal(b, m, deterministic)
}
func (m *OrderSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderSet.Merge(m, src)
}
func (m *OrderSet) XXX_Size() int {
	return xxx_messageInfo_OrderSet.Size(m)
}
func (m *OrderSet) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderSet.DiscardUnknown(m)
}

var xxx_messageInfo_OrderSet proto.InternalMessageInfo

func (m *OrderSet) GetTurn() uint32 {
	if m != nil {
		return m.Turn
	}
	return 0
}

func (m *OrderSet) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *OrderSet) GetDebugMessage() string {
	if m != nil {
		return m.DebugMessage
	}
	return ""
}

// Order to the game server. To be sent by players during the Listening phase.
type Order struct {
	// Types that are valid to be assigned to Action:
	//	*Order_Move
	//	*Order_Catch
	//	*Order_Kick
	//	*Order_Jump
	Action               isOrder_Action `protobuf_oneof:"action"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{7}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

type isOrder_Action interface {
	isOrder_Action()
}

type Order_Move struct {
	Move *Move `protobuf:"bytes,1,opt,name=move,proto3,oneof"`
}

type Order_Catch struct {
	Catch *Catch `protobuf:"bytes,2,opt,name=catch,proto3,oneof"`
}

type Order_Kick struct {
	Kick *Kick `protobuf:"bytes,3,opt,name=kick,proto3,oneof"`
}

type Order_Jump struct {
	Jump *Jump `protobuf:"bytes,4,opt,name=jump,proto3,oneof"`
}

func (*Order_Move) isOrder_Action() {}

func (*Order_Catch) isOrder_Action() {}

func (*Order_Kick) isOrder_Action() {}

func (*Order_Jump) isOrder_Action() {}

func (m *Order) GetAction() isOrder_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *Order) GetMove() *Move {
	if x, ok := m.GetAction().(*Order_Move); ok {
		return x.Move
	}
	return nil
}

func (m *Order) GetCatch() *Catch {
	if x, ok := m.GetAction().(*Order_Catch); ok {
		return x.Catch
	}
	return nil
}

func (m *Order) GetKick() *Kick {
	if x, ok := m.GetAction().(*Order_Kick); ok {
		return x.Kick
	}
	return nil
}

func (m *Order) GetJump() *Jump {
	if x, ok := m.GetAction().(*Order_Jump); ok {
		return x.Jump
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Order) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Order_Move)(nil),
		(*Order_Catch)(nil),
		(*Order_Kick)(nil),
		(*Order_Jump)(nil),
	}
}

// Order to ask the server to change the player velocity (direction and speed).
// This order replaces the current player velocity, and the new velocity attribute will be immediately processed
// in that turn. There is a limit speed to the player. The server will cap the velocity if the request is higher than
// the limit.
type Move struct {
	// The nex Velocity
	Velocity             *Velocity `protobuf:"bytes,1,opt,name=velocity,proto3" json:"velocity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Move) Reset()         { *m = Move{} }
func (m *Move) String() string { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()    {}
func (*Move) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{8}
}

func (m *Move) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Move.Unmarshal(m, b)
}
func (m *Move) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Move.Marshal(b, m, deterministic)
}
func (m *Move) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Move.Merge(m, src)
}
func (m *Move) XXX_Size() int {
	return xxx_messageInfo_Move.Size(m)
}
func (m *Move) XXX_DiscardUnknown() {
	xxx_messageInfo_Move.DiscardUnknown(m)
}

var xxx_messageInfo_Move proto.InternalMessageInfo

func (m *Move) GetVelocity() *Velocity {
	if m != nil {
		return m.Velocity
	}
	return nil
}

// Order to try to catch the ball. The player can only catch the ball when the player is touching the ball.
// Only one catching order can be executed in a turn. So, if more than one player try to catch the ball in the same
// turn, the first processed catch order will succeed, and the next ones will fail.
type Catch struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Catch) Reset()         { *m = Catch{} }
func (m *Catch) String() string { return proto.CompactTextString(m) }
func (*Catch) ProtoMessage()    {}
func (*Catch) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{9}
}

func (m *Catch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Catch.Unmarshal(m, b)
}
func (m *Catch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Catch.Marshal(b, m, deterministic)
}
func (m *Catch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Catch.Merge(m, src)
}
func (m *Catch) XXX_Size() int {
	return xxx_messageInfo_Catch.Size(m)
}
func (m *Catch) XXX_DiscardUnknown() {
	xxx_messageInfo_Catch.DiscardUnknown(m)
}

var xxx_messageInfo_Catch proto.InternalMessageInfo

// The kick order is only executed by the ball holder, and it is processed immediately.
// Important: The kick velocity is summed to the current ball velocity.
// The kick speed will suffer a power reduction proportionally to the player direction when the kick is not in the
// same direction of the player direction. The reduction is calculated based on the angle with the player direction
// using the formula `SpeedReducerFactor = 0.5 + (0.5 * ((180 - ang) / 180))`
// In summary, the speed will by reduced proportionally to the angle from 100% at 0 degrees until the limit of
// 50% at 180 degrees.
type Kick struct {
	// Kick velocity (it won't be necessarily the final ball velocity)
	Velocity             *Velocity `protobuf:"bytes,1,opt,name=velocity,proto3" json:"velocity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Kick) Reset()         { *m = Kick{} }
func (m *Kick) String() string { return proto.CompactTextString(m) }
func (*Kick) ProtoMessage()    {}
func (*Kick) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{10}
}

func (m *Kick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kick.Unmarshal(m, b)
}
func (m *Kick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kick.Marshal(b, m, deterministic)
}
func (m *Kick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kick.Merge(m, src)
}
func (m *Kick) XXX_Size() int {
	return xxx_messageInfo_Kick.Size(m)
}
func (m *Kick) XXX_DiscardUnknown() {
	xxx_messageInfo_Kick.DiscardUnknown(m)
}

var xxx_messageInfo_Kick proto.InternalMessageInfo

func (m *Kick) GetVelocity() *Velocity {
	if m != nil {
		return m.Velocity
	}
	return nil
}

// Changes the goalkeepers velocity in a higher speed.
// The goalkeepers may move kicker than other players when they jump, however the jump movement cannot be interrupted
// after triggered. (read specs to find out the number of turns the jump lasts)
type Jump struct {
	// Goalkeeper's velocity during the jump.
	Velocity             *Velocity `protobuf:"bytes,1,opt,name=velocity,proto3" json:"velocity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Jump) Reset()         { *m = Jump{} }
func (m *Jump) String() string { return proto.CompactTextString(m) }
func (*Jump) ProtoMessage()    {}
func (*Jump) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ddbe8bedca8f, []int{11}
}

func (m *Jump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Jump.Unmarshal(m, b)
}
func (m *Jump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Jump.Marshal(b, m, deterministic)
}
func (m *Jump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Jump.Merge(m, src)
}
func (m *Jump) XXX_Size() int {
	return xxx_messageInfo_Jump.Size(m)
}
func (m *Jump) XXX_DiscardUnknown() {
	xxx_messageInfo_Jump.DiscardUnknown(m)
}

var xxx_messageInfo_Jump proto.InternalMessageInfo

func (m *Jump) GetVelocity() *Velocity {
	if m != nil {
		return m.Velocity
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.GameSnapshot_Phase", GameSnapshot_Phase_name, GameSnapshot_Phase_value)
	proto.RegisterEnum("proto.Team_Side", Team_Side_name, Team_Side_value)
	proto.RegisterEnum("proto.OrderResponse_StatusCode", OrderResponse_StatusCode_name, OrderResponse_StatusCode_value)
	proto.RegisterType((*JoinRequest)(nil), "proto.JoinRequest")
	proto.RegisterType((*GameSnapshot)(nil), "proto.GameSnapshot")
	proto.RegisterType((*Team)(nil), "proto.Team")
	proto.RegisterType((*Player)(nil), "proto.Player")
	proto.RegisterType((*Ball)(nil), "proto.Ball")
	proto.RegisterType((*OrderResponse)(nil), "proto.OrderResponse")
	proto.RegisterType((*OrderSet)(nil), "proto.OrderSet")
	proto.RegisterType((*Order)(nil), "proto.Order")
	proto.RegisterType((*Move)(nil), "proto.Move")
	proto.RegisterType((*Catch)(nil), "proto.Catch")
	proto.RegisterType((*Kick)(nil), "proto.Kick")
	proto.RegisterType((*Jump)(nil), "proto.Jump")
}

func init() { proto.RegisterFile("proto/server.proto", fileDescriptor_b6e0ddbe8bedca8f) }

var fileDescriptor_b6e0ddbe8bedca8f = []byte{
	// 843 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xd1, 0x6e, 0xe3, 0x44,
	0x14, 0xcd, 0x34, 0x76, 0x9a, 0xdc, 0xd4, 0xad, 0x99, 0x5d, 0xa1, 0xd0, 0x97, 0x0d, 0xa6, 0x88,
	0x20, 0x44, 0x16, 0x12, 0x89, 0xf7, 0x6c, 0x89, 0xda, 0xee, 0x6e, 0x9d, 0x6a, 0x9c, 0xb6, 0xaa,
	0x78, 0xb0, 0xa6, 0xce, 0x68, 0x63, 0x6a, 0x7b, 0x82, 0x67, 0x12, 0xd4, 0x77, 0xfe, 0x80, 0x47,
	0x5e, 0xf8, 0x0f, 0x7e, 0x80, 0x5f, 0xe0, 0x6f, 0xd0, 0x1d, 0xdb, 0xdd, 0x24, 0x2a, 0x2a, 0xbb,
	0x4f, 0x99, 0x7b, 0xcf, 0xb9, 0x9e, 0x7b, 0xe7, 0x9c, 0x99, 0x00, 0x5d, 0xe4, 0x52, 0xcb, 0x97,
	0x4a, 0xe4, 0x2b, 0x91, 0xf7, 0x4d, 0x40, 0x6d, 0xf3, 0x73, 0xf8, 0xac, 0x80, 0x16, 0xf3, 0x7b,
	0x15, 0x47, 0xaa, 0xc0, 0xbc, 0xbf, 0x09, 0xb4, 0x5f, 0xcb, 0x38, 0x63, 0xe2, 0x97, 0xa5, 0x50,
	0x9a, 0x3e, 0x07, 0x5b, 0xcb, 0x3b, 0x91, 0x75, 0x48, 0x97, 0xf4, 0x5a, 0xac, 0x08, 0xe8, 0xd7,
	0xe0, 0x1a, 0x7a, 0x24, 0x93, 0x70, 0x25, 0x72, 0x15, 0xcb, 0xac, 0xb3, 0x63, 0x08, 0x07, 0x55,
	0xfe, 0xaa, 0x48, 0xd3, 0x6f, 0xa1, 0xa5, 0x05, 0x4f, 0x43, 0x15, 0xcf, 0x44, 0xa7, 0xde, 0x25,
	0xbd, 0xfd, 0x81, 0x5b, 0xec, 0xd5, 0x9f, 0x0a, 0x9e, 0xf6, 0x83, 0x78, 0x26, 0x58, 0x13, 0x29,
	0xb8, 0xa2, 0x9f, 0x42, 0x23, 0x5b, 0xa6, 0xb7, 0x22, 0xef, 0x58, 0x5d, 0xd2, 0x73, 0x58, 0x19,
	0xd1, 0xef, 0xc1, 0x89, 0xb3, 0x58, 0x87, 0x0b, 0xa9, 0x62, 0x8d, 0xdb, 0xd9, 0x5d, 0xd2, 0x6b,
	0x0f, 0xf6, 0xca, 0x4f, 0x5d, 0xc8, 0x38, 0xd3, 0x6c, 0x0f, 0x29, 0x17, 0x25, 0xc3, 0xfb, 0x7d,
	0x07, 0xf6, 0x4e, 0x78, 0x2a, 0x82, 0x8c, 0x2f, 0xd4, 0x5c, 0x6a, 0xfa, 0x12, 0x6c, 0xa5, 0xb9,
	0x16, 0x66, 0x96, 0xfd, 0xc1, 0x67, 0x65, 0xed, 0x3a, 0xa7, 0x7f, 0x31, 0xe7, 0x4a, 0xb0, 0x82,
	0x47, 0x29, 0x58, 0x7a, 0x99, 0x17, 0xa3, 0x39, 0xcc, 0xac, 0x69, 0x0f, 0x5a, 0x73, 0x99, 0x8a,
	0x10, 0x3b, 0x36, 0xf3, 0xb4, 0x07, 0xed, 0xb5, 0x79, 0x58, 0x13, 0x51, 0x5c, 0x21, 0x93, 0xff,
	0xca, 0xef, 0x0b, 0xa6, 0xf5, 0x08, 0x13, 0x51, 0xc3, 0x7c, 0x01, 0xd6, 0x2d, 0x4f, 0x92, 0x72,
	0xa6, 0x8a, 0xf4, 0x8a, 0x27, 0x09, 0x33, 0x80, 0x77, 0x06, 0xb6, 0x69, 0x8c, 0xb6, 0x61, 0xf7,
	0x7a, 0x74, 0x36, 0x3d, 0xf3, 0x4f, 0xdc, 0x1a, 0x75, 0xa0, 0x75, 0x32, 0x9e, 0x86, 0x6c, 0x3c,
	0xfa, 0xf1, 0xc6, 0x25, 0x18, 0xbe, 0x3d, 0x0b, 0xa6, 0x63, 0x1f, 0xd1, 0x1d, 0xa4, 0x5e, 0xbc,
	0x1d, 0xdd, 0x60, 0x50, 0xa7, 0x4d, 0xb0, 0x26, 0x57, 0x63, 0xe6, 0x46, 0xde, 0x1f, 0x04, 0x2c,
	0xb3, 0xe9, 0x57, 0xb0, 0xbb, 0x48, 0xf8, 0xbd, 0xc8, 0x55, 0x87, 0x74, 0xeb, 0xbd, 0xf6, 0xc0,
	0xa9, 0xce, 0xd2, 0x64, 0x59, 0x85, 0xe2, 0x29, 0xf8, 0x3c, 0x15, 0xa5, 0xc0, 0x66, 0x8d, 0xb6,
	0x08, 0x22, 0x99, 0x17, 0x8a, 0x3a, 0xac, 0x08, 0xe8, 0x11, 0x58, 0x46, 0x66, 0xeb, 0x3f, 0x64,
	0x36, 0xa8, 0x77, 0x08, 0x96, 0x91, 0xba, 0x09, 0xd6, 0xe9, 0xe4, 0x7c, 0xec, 0xd6, 0x70, 0x35,
	0xba, 0x1e, 0xdd, 0xb8, 0xc4, 0xfb, 0x87, 0x40, 0xa3, 0xd8, 0x7f, 0xcd, 0x09, 0x64, 0xc3, 0x09,
	0x3d, 0x68, 0x56, 0x12, 0x9b, 0x96, 0xb6, 0x4d, 0xf0, 0x80, 0xd2, 0x6f, 0xa0, 0xb9, 0x12, 0x89,
	0x8c, 0x62, 0x7d, 0x5f, 0x2a, 0x75, 0x50, 0x32, 0xaf, 0xca, 0x34, 0x7b, 0x20, 0x6c, 0xfa, 0xd4,
	0x7a, 0xd2, 0xa7, 0x1f, 0xe1, 0xc7, 0xdf, 0x08, 0x58, 0xa8, 0xe9, 0xc6, 0x04, 0xe4, 0x7f, 0x4f,
	0xb0, 0xf3, 0xd4, 0x04, 0x5f, 0x42, 0x63, 0x2e, 0x93, 0x99, 0xc8, 0xcb, 0x61, 0xb7, 0xf4, 0x2c,
	0x41, 0xef, 0x2f, 0x02, 0xce, 0x24, 0x9f, 0x89, 0x9c, 0x09, 0xb5, 0x90, 0x99, 0x12, 0x74, 0x08,
	0x56, 0x24, 0x67, 0xd5, 0xb5, 0x78, 0x51, 0x96, 0x6d, 0x70, 0xfa, 0x81, 0xe6, 0x7a, 0xa9, 0x8e,
	0x25, 0xaa, 0x88, 0x64, 0xda, 0x81, 0xdd, 0x99, 0xd0, 0x3c, 0x4e, 0x54, 0x69, 0x8c, 0x2a, 0xf4,
	0x7e, 0x02, 0x78, 0xcf, 0x46, 0x1b, 0x06, 0x97, 0xc7, 0xc7, 0xe3, 0x20, 0x70, 0x6b, 0x94, 0xc2,
	0xfe, 0xa5, 0xff, 0xc6, 0x9f, 0x5c, 0xfb, 0x21, 0x7a, 0x73, 0xcc, 0x5c, 0x42, 0x3f, 0x01, 0xc7,
	0x9f, 0x4c, 0xc3, 0x75, 0xeb, 0xee, 0x03, 0x5c, 0xb3, 0x89, 0x7f, 0x12, 0x4e, 0x2f, 0x99, 0xef,
	0xd6, 0x69, 0x0b, 0xec, 0xc9, 0xf4, 0xd4, 0xd8, 0x37, 0x86, 0xa6, 0x69, 0x2c, 0x10, 0xfa, 0xe1,
	0x7a, 0x92, 0xb5, 0xeb, 0x79, 0x04, 0x0d, 0x89, 0x38, 0x76, 0x55, 0x5f, 0x3b, 0xd9, 0x62, 0x9a,
	0x12, 0xa3, 0x5f, 0x80, 0x33, 0x13, 0xb7, 0xcb, 0x77, 0x61, 0x2a, 0x94, 0xe2, 0xef, 0x0a, 0x1b,
	0xb7, 0xd8, 0x9e, 0x49, 0x9e, 0x17, 0x39, 0xef, 0x4f, 0x02, 0xb6, 0x29, 0xa3, 0x9f, 0x83, 0x95,
	0xca, 0x95, 0x28, 0xc5, 0xaa, 0xee, 0xe7, 0xb9, 0x5c, 0x89, 0xd3, 0x1a, 0x33, 0x10, 0x3d, 0x02,
	0x3b, 0xe2, 0x3a, 0x9a, 0x6f, 0x59, 0xf2, 0x18, 0x73, 0xa7, 0x35, 0x56, 0x80, 0xf8, 0xa1, 0xbb,
	0x38, 0xba, 0xdb, 0x7a, 0x37, 0xde, 0xc4, 0xd1, 0x1d, 0x7e, 0x08, 0x21, 0xa4, 0xfc, 0xbc, 0x4c,
	0x17, 0x5b, 0x0f, 0xc6, 0xeb, 0x65, 0xba, 0x40, 0x0a, 0x42, 0xaf, 0x9a, 0xd0, 0xe0, 0x91, 0xb1,
	0xd4, 0x10, 0x2c, 0xec, 0x62, 0xc3, 0x27, 0xe4, 0x09, 0x9f, 0x78, 0xbb, 0x60, 0x9b, 0xb6, 0xb0,
	0x1a, 0xb7, 0xfe, 0xb0, 0xea, 0x21, 0x58, 0xd8, 0xcc, 0x07, 0x15, 0x0d, 0x14, 0x58, 0xf8, 0xca,
	0xd2, 0x1f, 0xa0, 0x85, 0x7f, 0x2e, 0x23, 0xf3, 0x00, 0xd1, 0x6a, 0xb6, 0xf7, 0x7f, 0x37, 0x87,
	0xcf, 0x1e, 0x79, 0x93, 0xbf, 0x23, 0x74, 0x08, 0x10, 0x88, 0x6c, 0x36, 0x29, 0xd4, 0x3b, 0x58,
	0xd7, 0x34, 0x10, 0xfa, 0xf0, 0xf9, 0x63, 0x96, 0xbd, 0x6d, 0x98, 0xe4, 0xf0, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xf9, 0x82, 0x3f, 0xd1, 0x03, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameClient interface {
	// JoinATeam allows the player to listen the server during the match.
	JoinATeam(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (Game_JoinATeamClient, error)
	// SendOrders allows the player to send others to the server when the game is on listening state.
	SendOrders(ctx context.Context, in *OrderSet, opts ...grpc.CallOption) (*OrderResponse, error)
}

type gameClient struct {
	cc *grpc.ClientConn
}

func NewGameClient(cc *grpc.ClientConn) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) JoinATeam(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (Game_JoinATeamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Game_serviceDesc.Streams[0], "/proto.Game/JoinATeam", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameJoinATeamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Game_JoinATeamClient interface {
	Recv() (*GameSnapshot, error)
	grpc.ClientStream
}

type gameJoinATeamClient struct {
	grpc.ClientStream
}

func (x *gameJoinATeamClient) Recv() (*GameSnapshot, error) {
	m := new(GameSnapshot)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gameClient) SendOrders(ctx context.Context, in *OrderSet, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/proto.Game/SendOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServer is the server API for Game service.
type GameServer interface {
	// JoinATeam allows the player to listen the server during the match.
	JoinATeam(*JoinRequest, Game_JoinATeamServer) error
	// SendOrders allows the player to send others to the server when the game is on listening state.
	SendOrders(context.Context, *OrderSet) (*OrderResponse, error)
}

func RegisterGameServer(s *grpc.Server, srv GameServer) {
	s.RegisterService(&_Game_serviceDesc, srv)
}

func _Game_JoinATeam_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameServer).JoinATeam(m, &gameJoinATeamServer{stream})
}

type Game_JoinATeamServer interface {
	Send(*GameSnapshot) error
	grpc.ServerStream
}

type gameJoinATeamServer struct {
	grpc.ServerStream
}

func (x *gameJoinATeamServer) Send(m *GameSnapshot) error {
	return x.ServerStream.SendMsg(m)
}

func _Game_SendOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).SendOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Game/SendOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).SendOrders(ctx, req.(*OrderSet))
	}
	return interceptor(ctx, in, info, handler)
}

var _Game_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Game",
	HandlerType: (*GameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendOrders",
			Handler:    _Game_SendOrders_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "JoinATeam",
			Handler:       _Game_JoinATeam_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/server.proto",
}
