language: go
go_import_path: github.com/lugobots/lugo4go/v2
git:
  depth: 1
env:
  - GO111MODULE=on
go: [1.13.x, 1.14.x]
os: [linux, osx]
install: true
script:
  - export GORACE=halt_on_error=1
  - go test -race -v ./...