// Code generated by MockGen. DO NOT EDIT.
// Source: ./contracts.go

// Package lugo4go is a generated GoMock package.
package lugo4go

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	mapper "github.com/lugobots/lugo4go/v3/mapper"
	proto "github.com/lugobots/lugo4go/v3/proto"
)

// MockTurnHandler is a mock of TurnHandler interface.
type MockTurnHandler struct {
	ctrl     *gomock.Controller
	recorder *MockTurnHandlerMockRecorder
}

// MockTurnHandlerMockRecorder is the mock recorder for MockTurnHandler.
type MockTurnHandlerMockRecorder struct {
	mock *MockTurnHandler
}

// NewMockTurnHandler creates a new mock instance.
func NewMockTurnHandler(ctrl *gomock.Controller) *MockTurnHandler {
	mock := &MockTurnHandler{ctrl: ctrl}
	mock.recorder = &MockTurnHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTurnHandler) EXPECT() *MockTurnHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockTurnHandler) Handle(ctx context.Context, snapshot *proto.GameSnapshot) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Handle", ctx, snapshot)
}

// Handle indicates an expected call of Handle.
func (mr *MockTurnHandlerMockRecorder) Handle(ctx, snapshot interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockTurnHandler)(nil).Handle), ctx, snapshot)
}

// MockOrderSender is a mock of orderSender interface.
type MockOrderSender struct {
	ctrl     *gomock.Controller
	recorder *MockOrderSenderMockRecorder
}

// MockOrderSenderMockRecorder is the mock recorder for MockOrderSender.
type MockOrderSenderMockRecorder struct {
	mock *MockOrderSender
}

// NewMockOrderSender creates a new mock instance.
func NewMockOrderSender(ctrl *gomock.Controller) *MockOrderSender {
	mock := &MockOrderSender{ctrl: ctrl}
	mock.recorder = &MockOrderSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderSender) EXPECT() *MockOrderSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockOrderSender) Send(ctx context.Context, turn uint32, orders []proto.PlayerOrder, debugMsg string) (*proto.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, turn, orders, debugMsg)
	ret0, _ := ret[0].(*proto.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockOrderSenderMockRecorder) Send(ctx, turn, orders, debugMsg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockOrderSender)(nil).Send), ctx, turn, orders, debugMsg)
}

// MockTurnOrdersSender is a mock of TurnOrdersSender interface.
type MockTurnOrdersSender struct {
	ctrl     *gomock.Controller
	recorder *MockTurnOrdersSenderMockRecorder
}

// MockTurnOrdersSenderMockRecorder is the mock recorder for MockTurnOrdersSender.
type MockTurnOrdersSenderMockRecorder struct {
	mock *MockTurnOrdersSender
}

// NewMockTurnOrdersSender creates a new mock instance.
func NewMockTurnOrdersSender(ctrl *gomock.Controller) *MockTurnOrdersSender {
	mock := &MockTurnOrdersSender{ctrl: ctrl}
	mock.recorder = &MockTurnOrdersSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTurnOrdersSender) EXPECT() *MockTurnOrdersSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockTurnOrdersSender) Send(ctx context.Context, orders []proto.PlayerOrder, debugMsg string) (*proto.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, orders, debugMsg)
	ret0, _ := ret[0].(*proto.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockTurnOrdersSenderMockRecorder) Send(ctx, orders, debugMsg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTurnOrdersSender)(nil).Send), ctx, orders, debugMsg)
}

// MockSnapshotInspector is a mock of SnapshotInspector interface.
type MockSnapshotInspector struct {
	ctrl     *gomock.Controller
	recorder *MockSnapshotInspectorMockRecorder
}

// MockSnapshotInspectorMockRecorder is the mock recorder for MockSnapshotInspector.
type MockSnapshotInspectorMockRecorder struct {
	mock *MockSnapshotInspector
}

// NewMockSnapshotInspector creates a new mock instance.
func NewMockSnapshotInspector(ctrl *gomock.Controller) *MockSnapshotInspector {
	mock := &MockSnapshotInspector{ctrl: ctrl}
	mock.recorder = &MockSnapshotInspectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnapshotInspector) EXPECT() *MockSnapshotInspectorMockRecorder {
	return m.recorder
}

// GetBall mocks base method.
func (m *MockSnapshotInspector) GetBall() *proto.Ball {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBall")
	ret0, _ := ret[0].(*proto.Ball)
	return ret0
}

// GetBall indicates an expected call of GetBall.
func (mr *MockSnapshotInspectorMockRecorder) GetBall() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBall", reflect.TypeOf((*MockSnapshotInspector)(nil).GetBall))
}

// GetBallHolder mocks base method.
func (m *MockSnapshotInspector) GetBallHolder() (*proto.Player, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBallHolder")
	ret0, _ := ret[0].(*proto.Player)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetBallHolder indicates an expected call of GetBallHolder.
func (mr *MockSnapshotInspectorMockRecorder) GetBallHolder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBallHolder", reflect.TypeOf((*MockSnapshotInspector)(nil).GetBallHolder))
}

// GetMe mocks base method.
func (m *MockSnapshotInspector) GetMe() *proto.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMe")
	ret0, _ := ret[0].(*proto.Player)
	return ret0
}

// GetMe indicates an expected call of GetMe.
func (mr *MockSnapshotInspectorMockRecorder) GetMe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMe", reflect.TypeOf((*MockSnapshotInspector)(nil).GetMe))
}

// GetMyTeam mocks base method.
func (m *MockSnapshotInspector) GetMyTeam() *proto.Team {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyTeam")
	ret0, _ := ret[0].(*proto.Team)
	return ret0
}

// GetMyTeam indicates an expected call of GetMyTeam.
func (mr *MockSnapshotInspectorMockRecorder) GetMyTeam() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyTeam", reflect.TypeOf((*MockSnapshotInspector)(nil).GetMyTeam))
}

// GetMyTeamPlayers mocks base method.
func (m *MockSnapshotInspector) GetMyTeamPlayers() []*proto.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyTeamPlayers")
	ret0, _ := ret[0].([]*proto.Player)
	return ret0
}

// GetMyTeamPlayers indicates an expected call of GetMyTeamPlayers.
func (mr *MockSnapshotInspectorMockRecorder) GetMyTeamPlayers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyTeamPlayers", reflect.TypeOf((*MockSnapshotInspector)(nil).GetMyTeamPlayers))
}

// GetMyTeamSide mocks base method.
func (m *MockSnapshotInspector) GetMyTeamSide() proto.Team_Side {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyTeamSide")
	ret0, _ := ret[0].(proto.Team_Side)
	return ret0
}

// GetMyTeamSide indicates an expected call of GetMyTeamSide.
func (mr *MockSnapshotInspectorMockRecorder) GetMyTeamSide() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyTeamSide", reflect.TypeOf((*MockSnapshotInspector)(nil).GetMyTeamSide))
}

// GetOpponentMyTeam mocks base method.
func (m *MockSnapshotInspector) GetOpponentMyTeam() *proto.Team {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpponentMyTeam")
	ret0, _ := ret[0].(*proto.Team)
	return ret0
}

// GetOpponentMyTeam indicates an expected call of GetOpponentMyTeam.
func (mr *MockSnapshotInspectorMockRecorder) GetOpponentMyTeam() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpponentMyTeam", reflect.TypeOf((*MockSnapshotInspector)(nil).GetOpponentMyTeam))
}

// GetOpponentPlayers mocks base method.
func (m *MockSnapshotInspector) GetOpponentPlayers() []*proto.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpponentPlayers")
	ret0, _ := ret[0].([]*proto.Player)
	return ret0
}

// GetOpponentPlayers indicates an expected call of GetOpponentPlayers.
func (mr *MockSnapshotInspectorMockRecorder) GetOpponentPlayers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpponentPlayers", reflect.TypeOf((*MockSnapshotInspector)(nil).GetOpponentPlayers))
}

// GetOpponentSide mocks base method.
func (m *MockSnapshotInspector) GetOpponentSide() proto.Team_Side {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpponentSide")
	ret0, _ := ret[0].(proto.Team_Side)
	return ret0
}

// GetOpponentSide indicates an expected call of GetOpponentSide.
func (mr *MockSnapshotInspectorMockRecorder) GetOpponentSide() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpponentSide", reflect.TypeOf((*MockSnapshotInspector)(nil).GetOpponentSide))
}

// GetPlayer mocks base method.
func (m *MockSnapshotInspector) GetPlayer(side proto.Team_Side, number int) *proto.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayer", side, number)
	ret0, _ := ret[0].(*proto.Player)
	return ret0
}

// GetPlayer indicates an expected call of GetPlayer.
func (mr *MockSnapshotInspectorMockRecorder) GetPlayer(side, number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayer", reflect.TypeOf((*MockSnapshotInspector)(nil).GetPlayer), side, number)
}

// GetSnapshot mocks base method.
func (m *MockSnapshotInspector) GetSnapshot() *proto.GameSnapshot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSnapshot")
	ret0, _ := ret[0].(*proto.GameSnapshot)
	return ret0
}

// GetSnapshot indicates an expected call of GetSnapshot.
func (mr *MockSnapshotInspectorMockRecorder) GetSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSnapshot", reflect.TypeOf((*MockSnapshotInspector)(nil).GetSnapshot))
}

// GetTeam mocks base method.
func (m *MockSnapshotInspector) GetTeam(side proto.Team_Side) *proto.Team {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", side)
	ret0, _ := ret[0].(*proto.Team)
	return ret0
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockSnapshotInspectorMockRecorder) GetTeam(side interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockSnapshotInspector)(nil).GetTeam), side)
}

// IsBallHolder mocks base method.
func (m *MockSnapshotInspector) IsBallHolder(player *proto.Player) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBallHolder", player)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBallHolder indicates an expected call of IsBallHolder.
func (mr *MockSnapshotInspectorMockRecorder) IsBallHolder(player interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBallHolder", reflect.TypeOf((*MockSnapshotInspector)(nil).IsBallHolder), player)
}

// MakeOrderCatch mocks base method.
func (m *MockSnapshotInspector) MakeOrderCatch() *proto.Order_Catch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeOrderCatch")
	ret0, _ := ret[0].(*proto.Order_Catch)
	return ret0
}

// MakeOrderCatch indicates an expected call of MakeOrderCatch.
func (mr *MockSnapshotInspectorMockRecorder) MakeOrderCatch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeOrderCatch", reflect.TypeOf((*MockSnapshotInspector)(nil).MakeOrderCatch))
}

// MakeOrderJump mocks base method.
func (m *MockSnapshotInspector) MakeOrderJump(target proto.Point, speed float64) (*proto.Order_Jump, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeOrderJump", target, speed)
	ret0, _ := ret[0].(*proto.Order_Jump)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeOrderJump indicates an expected call of MakeOrderJump.
func (mr *MockSnapshotInspectorMockRecorder) MakeOrderJump(target, speed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeOrderJump", reflect.TypeOf((*MockSnapshotInspector)(nil).MakeOrderJump), target, speed)
}

// MakeOrderKick mocks base method.
func (m *MockSnapshotInspector) MakeOrderKick(target proto.Point, speed float64) (*proto.Order_Kick, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeOrderKick", target, speed)
	ret0, _ := ret[0].(*proto.Order_Kick)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeOrderKick indicates an expected call of MakeOrderKick.
func (mr *MockSnapshotInspectorMockRecorder) MakeOrderKick(target, speed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeOrderKick", reflect.TypeOf((*MockSnapshotInspector)(nil).MakeOrderKick), target, speed)
}

// MakeOrderKickMaxSpeed mocks base method.
func (m *MockSnapshotInspector) MakeOrderKickMaxSpeed(target proto.Point) (*proto.Order_Kick, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeOrderKickMaxSpeed", target)
	ret0, _ := ret[0].(*proto.Order_Kick)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeOrderKickMaxSpeed indicates an expected call of MakeOrderKickMaxSpeed.
func (mr *MockSnapshotInspectorMockRecorder) MakeOrderKickMaxSpeed(target interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeOrderKickMaxSpeed", reflect.TypeOf((*MockSnapshotInspector)(nil).MakeOrderKickMaxSpeed), target)
}

// MakeOrderMoveByDirection mocks base method.
func (m *MockSnapshotInspector) MakeOrderMoveByDirection(direction mapper.Direction, speed float64) (*proto.Order_Move, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeOrderMoveByDirection", direction, speed)
	ret0, _ := ret[0].(*proto.Order_Move)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeOrderMoveByDirection indicates an expected call of MakeOrderMoveByDirection.
func (mr *MockSnapshotInspectorMockRecorder) MakeOrderMoveByDirection(direction, speed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeOrderMoveByDirection", reflect.TypeOf((*MockSnapshotInspector)(nil).MakeOrderMoveByDirection), direction, speed)
}

// MakeOrderMoveFromPoint mocks base method.
func (m *MockSnapshotInspector) MakeOrderMoveFromPoint(origin, target proto.Point, speed float64) (*proto.Order_Move, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeOrderMoveFromPoint", origin, target, speed)
	ret0, _ := ret[0].(*proto.Order_Move)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeOrderMoveFromPoint indicates an expected call of MakeOrderMoveFromPoint.
func (mr *MockSnapshotInspectorMockRecorder) MakeOrderMoveFromPoint(origin, target, speed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeOrderMoveFromPoint", reflect.TypeOf((*MockSnapshotInspector)(nil).MakeOrderMoveFromPoint), origin, target, speed)
}

// MakeOrderMoveFromVector mocks base method.
func (m *MockSnapshotInspector) MakeOrderMoveFromVector(vector proto.Vector, speed float64) (*proto.Order_Move, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeOrderMoveFromVector", vector, speed)
	ret0, _ := ret[0].(*proto.Order_Move)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeOrderMoveFromVector indicates an expected call of MakeOrderMoveFromVector.
func (mr *MockSnapshotInspectorMockRecorder) MakeOrderMoveFromVector(vector, speed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeOrderMoveFromVector", reflect.TypeOf((*MockSnapshotInspector)(nil).MakeOrderMoveFromVector), vector, speed)
}

// MakeOrderMoveMaxSpeed mocks base method.
func (m *MockSnapshotInspector) MakeOrderMoveMaxSpeed(target proto.Point) (*proto.Order_Move, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeOrderMoveMaxSpeed", target)
	ret0, _ := ret[0].(*proto.Order_Move)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeOrderMoveMaxSpeed indicates an expected call of MakeOrderMoveMaxSpeed.
func (mr *MockSnapshotInspectorMockRecorder) MakeOrderMoveMaxSpeed(target interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeOrderMoveMaxSpeed", reflect.TypeOf((*MockSnapshotInspector)(nil).MakeOrderMoveMaxSpeed), target)
}

// MockBot is a mock of Bot interface.
type MockBot struct {
	ctrl     *gomock.Controller
	recorder *MockBotMockRecorder
}

// MockBotMockRecorder is the mock recorder for MockBot.
type MockBotMockRecorder struct {
	mock *MockBot
}

// NewMockBot creates a new mock instance.
func NewMockBot(ctrl *gomock.Controller) *MockBot {
	mock := &MockBot{ctrl: ctrl}
	mock.recorder = &MockBotMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBot) EXPECT() *MockBotMockRecorder {
	return m.recorder
}

// AsGoalkeeper mocks base method.
func (m *MockBot) AsGoalkeeper(ctx context.Context, snapshot SnapshotInspector, state PlayerState) ([]proto.PlayerOrder, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsGoalkeeper", ctx, snapshot, state)
	ret0, _ := ret[0].([]proto.PlayerOrder)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AsGoalkeeper indicates an expected call of AsGoalkeeper.
func (mr *MockBotMockRecorder) AsGoalkeeper(ctx, snapshot, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsGoalkeeper", reflect.TypeOf((*MockBot)(nil).AsGoalkeeper), ctx, snapshot, state)
}

// OnDefending mocks base method.
func (m *MockBot) OnDefending(ctx context.Context, snapshot SnapshotInspector) ([]proto.PlayerOrder, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnDefending", ctx, snapshot)
	ret0, _ := ret[0].([]proto.PlayerOrder)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// OnDefending indicates an expected call of OnDefending.
func (mr *MockBotMockRecorder) OnDefending(ctx, snapshot interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnDefending", reflect.TypeOf((*MockBot)(nil).OnDefending), ctx, snapshot)
}

// OnDisputing mocks base method.
func (m *MockBot) OnDisputing(ctx context.Context, snapshot SnapshotInspector) ([]proto.PlayerOrder, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnDisputing", ctx, snapshot)
	ret0, _ := ret[0].([]proto.PlayerOrder)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// OnDisputing indicates an expected call of OnDisputing.
func (mr *MockBotMockRecorder) OnDisputing(ctx, snapshot interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnDisputing", reflect.TypeOf((*MockBot)(nil).OnDisputing), ctx, snapshot)
}

// OnHolding mocks base method.
func (m *MockBot) OnHolding(ctx context.Context, snapshot SnapshotInspector) ([]proto.PlayerOrder, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnHolding", ctx, snapshot)
	ret0, _ := ret[0].([]proto.PlayerOrder)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// OnHolding indicates an expected call of OnHolding.
func (mr *MockBotMockRecorder) OnHolding(ctx, snapshot interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnHolding", reflect.TypeOf((*MockBot)(nil).OnHolding), ctx, snapshot)
}

// OnSupporting mocks base method.
func (m *MockBot) OnSupporting(ctx context.Context, snapshot SnapshotInspector) ([]proto.PlayerOrder, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnSupporting", ctx, snapshot)
	ret0, _ := ret[0].([]proto.PlayerOrder)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// OnSupporting indicates an expected call of OnSupporting.
func (mr *MockBotMockRecorder) OnSupporting(ctx, snapshot interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnSupporting", reflect.TypeOf((*MockBot)(nil).OnSupporting), ctx, snapshot)
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), args...)
}

// Debugf mocks base method.
func (m *MockLogger) Debugf(template string, args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugf", varargs...)
}

// Debugf indicates an expected call of Debugf.
func (mr *MockLoggerMockRecorder) Debugf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugf", reflect.TypeOf((*MockLogger)(nil).Debugf), varargs...)
}

// Errorf mocks base method.
func (m *MockLogger) Errorf(template string, args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockLoggerMockRecorder) Errorf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockLogger)(nil).Errorf), varargs...)
}

// Fatalf mocks base method.
func (m *MockLogger) Fatalf(template string, args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatalf", varargs...)
}

// Fatalf indicates an expected call of Fatalf.
func (mr *MockLoggerMockRecorder) Fatalf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatalf", reflect.TypeOf((*MockLogger)(nil).Fatalf), varargs...)
}

// Infof mocks base method.
func (m *MockLogger) Infof(template string, args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockLoggerMockRecorder) Infof(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockLogger)(nil).Infof), varargs...)
}

// Warnf mocks base method.
func (m *MockLogger) Warnf(template string, args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warnf", varargs...)
}

// Warnf indicates an expected call of Warnf.
func (mr *MockLoggerMockRecorder) Warnf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnf", reflect.TypeOf((*MockLogger)(nil).Warnf), varargs...)
}

// MockMapper is a mock of Mapper interface.
type MockMapper struct {
	ctrl     *gomock.Controller
	recorder *MockMapperMockRecorder
}

// MockMapperMockRecorder is the mock recorder for MockMapper.
type MockMapperMockRecorder struct {
	mock *MockMapper
}

// NewMockMapper creates a new mock instance.
func NewMockMapper(ctrl *gomock.Controller) *MockMapper {
	mock := &MockMapper{ctrl: ctrl}
	mock.recorder = &MockMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapper) EXPECT() *MockMapperMockRecorder {
	return m.recorder
}

// AwayTeamGoal mocks base method.
func (m *MockMapper) AwayTeamGoal() mapper.Goal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AwayTeamGoal")
	ret0, _ := ret[0].(mapper.Goal)
	return ret0
}

// AwayTeamGoal indicates an expected call of AwayTeamGoal.
func (mr *MockMapperMockRecorder) AwayTeamGoal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AwayTeamGoal", reflect.TypeOf((*MockMapper)(nil).AwayTeamGoal))
}

// FieldCenter mocks base method.
func (m *MockMapper) FieldCenter() proto.Point {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FieldCenter")
	ret0, _ := ret[0].(proto.Point)
	return ret0
}

// FieldCenter indicates an expected call of FieldCenter.
func (mr *MockMapperMockRecorder) FieldCenter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FieldCenter", reflect.TypeOf((*MockMapper)(nil).FieldCenter))
}

// GetMyTeamGoal mocks base method.
func (m *MockMapper) GetMyTeamGoal() mapper.Goal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyTeamGoal")
	ret0, _ := ret[0].(mapper.Goal)
	return ret0
}

// GetMyTeamGoal indicates an expected call of GetMyTeamGoal.
func (mr *MockMapperMockRecorder) GetMyTeamGoal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyTeamGoal", reflect.TypeOf((*MockMapper)(nil).GetMyTeamGoal))
}

// GetOpponentGoal mocks base method.
func (m *MockMapper) GetOpponentGoal() mapper.Goal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpponentGoal")
	ret0, _ := ret[0].(mapper.Goal)
	return ret0
}

// GetOpponentGoal indicates an expected call of GetOpponentGoal.
func (mr *MockMapperMockRecorder) GetOpponentGoal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpponentGoal", reflect.TypeOf((*MockMapper)(nil).GetOpponentGoal))
}

// GetPointRegion mocks base method.
func (m *MockMapper) GetPointRegion(point *proto.Point) (mapper.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPointRegion", point)
	ret0, _ := ret[0].(mapper.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPointRegion indicates an expected call of GetPointRegion.
func (mr *MockMapperMockRecorder) GetPointRegion(point interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPointRegion", reflect.TypeOf((*MockMapper)(nil).GetPointRegion), point)
}

// GetRegion mocks base method.
func (m *MockMapper) GetRegion(col, row int) (mapper.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegion", col, row)
	ret0, _ := ret[0].(mapper.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegion indicates an expected call of GetRegion.
func (mr *MockMapperMockRecorder) GetRegion(col, row interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegion", reflect.TypeOf((*MockMapper)(nil).GetRegion), col, row)
}

// GetTeamsGoal mocks base method.
func (m *MockMapper) GetTeamsGoal(side proto.Team_Side) mapper.Goal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamsGoal", side)
	ret0, _ := ret[0].(mapper.Goal)
	return ret0
}

// GetTeamsGoal indicates an expected call of GetTeamsGoal.
func (mr *MockMapperMockRecorder) GetTeamsGoal(side interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamsGoal", reflect.TypeOf((*MockMapper)(nil).GetTeamsGoal), side)
}

// HomeTeamGoal mocks base method.
func (m *MockMapper) HomeTeamGoal() mapper.Goal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HomeTeamGoal")
	ret0, _ := ret[0].(mapper.Goal)
	return ret0
}

// HomeTeamGoal indicates an expected call of HomeTeamGoal.
func (mr *MockMapperMockRecorder) HomeTeamGoal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HomeTeamGoal", reflect.TypeOf((*MockMapper)(nil).HomeTeamGoal))
}

// MockRegion is a mock of Region interface.
type MockRegion struct {
	ctrl     *gomock.Controller
	recorder *MockRegionMockRecorder
}

// MockRegionMockRecorder is the mock recorder for MockRegion.
type MockRegionMockRecorder struct {
	mock *MockRegion
}

// NewMockRegion creates a new mock instance.
func NewMockRegion(ctrl *gomock.Controller) *MockRegion {
	mock := &MockRegion{ctrl: ctrl}
	mock.recorder = &MockRegionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegion) EXPECT() *MockRegionMockRecorder {
	return m.recorder
}

// Back mocks base method.
func (m *MockRegion) Back() mapper.Region {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Back")
	ret0, _ := ret[0].(mapper.Region)
	return ret0
}

// Back indicates an expected call of Back.
func (mr *MockRegionMockRecorder) Back() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Back", reflect.TypeOf((*MockRegion)(nil).Back))
}

// Center mocks base method.
func (m *MockRegion) Center() *proto.Point {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Center")
	ret0, _ := ret[0].(*proto.Point)
	return ret0
}

// Center indicates an expected call of Center.
func (mr *MockRegionMockRecorder) Center() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Center", reflect.TypeOf((*MockRegion)(nil).Center))
}

// Col mocks base method.
func (m *MockRegion) Col() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Col")
	ret0, _ := ret[0].(int)
	return ret0
}

// Col indicates an expected call of Col.
func (mr *MockRegionMockRecorder) Col() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Col", reflect.TypeOf((*MockRegion)(nil).Col))
}

// Eq mocks base method.
func (m *MockRegion) Eq(region mapper.Region) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Eq", region)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Eq indicates an expected call of Eq.
func (mr *MockRegionMockRecorder) Eq(region interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Eq", reflect.TypeOf((*MockRegion)(nil).Eq), region)
}

// Front mocks base method.
func (m *MockRegion) Front() mapper.Region {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Front")
	ret0, _ := ret[0].(mapper.Region)
	return ret0
}

// Front indicates an expected call of Front.
func (mr *MockRegionMockRecorder) Front() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Front", reflect.TypeOf((*MockRegion)(nil).Front))
}

// Left mocks base method.
func (m *MockRegion) Left() mapper.Region {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Left")
	ret0, _ := ret[0].(mapper.Region)
	return ret0
}

// Left indicates an expected call of Left.
func (mr *MockRegionMockRecorder) Left() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Left", reflect.TypeOf((*MockRegion)(nil).Left))
}

// Right mocks base method.
func (m *MockRegion) Right() mapper.Region {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Right")
	ret0, _ := ret[0].(mapper.Region)
	return ret0
}

// Right indicates an expected call of Right.
func (mr *MockRegionMockRecorder) Right() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Right", reflect.TypeOf((*MockRegion)(nil).Right))
}

// Row mocks base method.
func (m *MockRegion) Row() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Row")
	ret0, _ := ret[0].(int)
	return ret0
}

// Row indicates an expected call of Row.
func (mr *MockRegionMockRecorder) Row() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Row", reflect.TypeOf((*MockRegion)(nil).Row))
}

// String mocks base method.
func (m *MockRegion) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockRegionMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockRegion)(nil).String))
}
