// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.1
// source: remote.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandResponse_StatusCode int32

const (
	CommandResponse_SUCCESS           CommandResponse_StatusCode = 0
	CommandResponse_INVALID_VALUE     CommandResponse_StatusCode = 1
	CommandResponse_DEADLINE_EXCEEDED CommandResponse_StatusCode = 2
	CommandResponse_OTHER             CommandResponse_StatusCode = 99
)

// Enum value maps for CommandResponse_StatusCode.
var (
	CommandResponse_StatusCode_name = map[int32]string{
		0:  "SUCCESS",
		1:  "INVALID_VALUE",
		2:  "DEADLINE_EXCEEDED",
		99: "OTHER",
	}
	CommandResponse_StatusCode_value = map[string]int32{
		"SUCCESS":           0,
		"INVALID_VALUE":     1,
		"DEADLINE_EXCEEDED": 2,
		"OTHER":             99,
	}
)

func (x CommandResponse_StatusCode) Enum() *CommandResponse_StatusCode {
	p := new(CommandResponse_StatusCode)
	*p = x
	return p
}

func (x CommandResponse_StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandResponse_StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_proto_enumTypes[0].Descriptor()
}

func (CommandResponse_StatusCode) Type() protoreflect.EnumType {
	return &file_remote_proto_enumTypes[0]
}

func (x CommandResponse_StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandResponse_StatusCode.Descriptor instead.
func (CommandResponse_StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{6, 0}
}

type PauseResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseResumeRequest) Reset() {
	*x = PauseResumeRequest{}
	mi := &file_remote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseResumeRequest) ProtoMessage() {}

func (x *PauseResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseResumeRequest.ProtoReflect.Descriptor instead.
func (*PauseResumeRequest) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{0}
}

type NextTurnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextTurnRequest) Reset() {
	*x = NextTurnRequest{}
	mi := &file_remote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextTurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextTurnRequest) ProtoMessage() {}

func (x *NextTurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextTurnRequest.ProtoReflect.Descriptor instead.
func (*NextTurnRequest) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{1}
}

type NextOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextOrderRequest) Reset() {
	*x = NextOrderRequest{}
	mi := &file_remote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextOrderRequest) ProtoMessage() {}

func (x *NextOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextOrderRequest.ProtoReflect.Descriptor instead.
func (*NextOrderRequest) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{2}
}

type BallProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Point                 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Velocity      *Velocity              `protobuf:"bytes,2,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Holder        *Player                `protobuf:"bytes,3,opt,name=holder,proto3" json:"holder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BallProperties) Reset() {
	*x = BallProperties{}
	mi := &file_remote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BallProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallProperties) ProtoMessage() {}

func (x *BallProperties) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallProperties.ProtoReflect.Descriptor instead.
func (*BallProperties) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{3}
}

func (x *BallProperties) GetPosition() *Point {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *BallProperties) GetVelocity() *Velocity {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *BallProperties) GetHolder() *Player {
	if x != nil {
		return x.Holder
	}
	return nil
}

type PlayerProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Side          Team_Side              `protobuf:"varint,1,opt,name=side,proto3,enum=lugo.Team_Side" json:"side,omitempty"`
	Number        uint32                 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Position      *Point                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Velocity      *Velocity              `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerProperties) Reset() {
	*x = PlayerProperties{}
	mi := &file_remote_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProperties) ProtoMessage() {}

func (x *PlayerProperties) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProperties.ProtoReflect.Descriptor instead.
func (*PlayerProperties) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerProperties) GetSide() Team_Side {
	if x != nil {
		return x.Side
	}
	return Team_HOME
}

func (x *PlayerProperties) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *PlayerProperties) GetPosition() *Point {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerProperties) GetVelocity() *Velocity {
	if x != nil {
		return x.Velocity
	}
	return nil
}

type GameProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turn          uint32                 `protobuf:"varint,1,opt,name=turn,proto3" json:"turn,omitempty"`
	HomeScore     uint32                 `protobuf:"varint,2,opt,name=home_score,json=homeScore,proto3" json:"home_score,omitempty"`
	AwayScore     uint32                 `protobuf:"varint,3,opt,name=away_score,json=awayScore,proto3" json:"away_score,omitempty"`
	FrameInterval int64                  `protobuf:"varint,4,opt,name=frame_interval,json=frameInterval,proto3" json:"frame_interval,omitempty"`
	ShotClock     *ShotClock             `protobuf:"bytes,5,opt,name=shot_clock,json=shotClock,proto3" json:"shot_clock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameProperties) Reset() {
	*x = GameProperties{}
	mi := &file_remote_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameProperties) ProtoMessage() {}

func (x *GameProperties) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameProperties.ProtoReflect.Descriptor instead.
func (*GameProperties) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{5}
}

func (x *GameProperties) GetTurn() uint32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *GameProperties) GetHomeScore() uint32 {
	if x != nil {
		return x.HomeScore
	}
	return 0
}

func (x *GameProperties) GetAwayScore() uint32 {
	if x != nil {
		return x.AwayScore
	}
	return 0
}

func (x *GameProperties) GetFrameInterval() int64 {
	if x != nil {
		return x.FrameInterval
	}
	return 0
}

func (x *GameProperties) GetShotClock() *ShotClock {
	if x != nil {
		return x.ShotClock
	}
	return nil
}

type CommandResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Code          CommandResponse_StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=lugo.CommandResponse_StatusCode" json:"code,omitempty"`
	GameSnapshot  *GameSnapshot              `protobuf:"bytes,2,opt,name=game_snapshot,json=gameSnapshot,proto3" json:"game_snapshot,omitempty"`
	Details       string                     `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_remote_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{6}
}

func (x *CommandResponse) GetCode() CommandResponse_StatusCode {
	if x != nil {
		return x.Code
	}
	return CommandResponse_SUCCESS
}

func (x *CommandResponse) GetGameSnapshot() *GameSnapshot {
	if x != nil {
		return x.GameSnapshot
	}
	return nil
}

func (x *CommandResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type ResumeListeningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeListeningRequest) Reset() {
	*x = ResumeListeningRequest{}
	mi := &file_remote_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeListeningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeListeningRequest) ProtoMessage() {}

func (x *ResumeListeningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeListeningRequest.ProtoReflect.Descriptor instead.
func (*ResumeListeningRequest) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{7}
}

type ResumeListeningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeListeningResponse) Reset() {
	*x = ResumeListeningResponse{}
	mi := &file_remote_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeListeningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeListeningResponse) ProtoMessage() {}

func (x *ResumeListeningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeListeningResponse.ProtoReflect.Descriptor instead.
func (*ResumeListeningResponse) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{8}
}

type ResetPlayerPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPlayerPositionsRequest) Reset() {
	*x = ResetPlayerPositionsRequest{}
	mi := &file_remote_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPlayerPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPlayerPositionsRequest) ProtoMessage() {}

func (x *ResetPlayerPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPlayerPositionsRequest.ProtoReflect.Descriptor instead.
func (*ResetPlayerPositionsRequest) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{9}
}

type ResetGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetGameRequest) Reset() {
	*x = ResetGameRequest{}
	mi := &file_remote_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetGameRequest) ProtoMessage() {}

func (x *ResetGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetGameRequest.ProtoReflect.Descriptor instead.
func (*ResetGameRequest) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{10}
}

type ResetPlayerPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameSnapshot  *GameSnapshot          `protobuf:"bytes,1,opt,name=game_snapshot,json=gameSnapshot,proto3" json:"game_snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPlayerPositionsResponse) Reset() {
	*x = ResetPlayerPositionsResponse{}
	mi := &file_remote_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPlayerPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPlayerPositionsResponse) ProtoMessage() {}

func (x *ResetPlayerPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPlayerPositionsResponse.ProtoReflect.Descriptor instead.
func (*ResetPlayerPositionsResponse) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{11}
}

func (x *ResetPlayerPositionsResponse) GetGameSnapshot() *GameSnapshot {
	if x != nil {
		return x.GameSnapshot
	}
	return nil
}

type GameSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameSnapshotRequest) Reset() {
	*x = GameSnapshotRequest{}
	mi := &file_remote_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSnapshotRequest) ProtoMessage() {}

func (x *GameSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GameSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{12}
}

type GameSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameSnapshot  *GameSnapshot          `protobuf:"bytes,1,opt,name=game_snapshot,json=gameSnapshot,proto3" json:"game_snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameSnapshotResponse) Reset() {
	*x = GameSnapshotResponse{}
	mi := &file_remote_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSnapshotResponse) ProtoMessage() {}

func (x *GameSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GameSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{13}
}

func (x *GameSnapshotResponse) GetGameSnapshot() *GameSnapshot {
	if x != nil {
		return x.GameSnapshot
	}
	return nil
}

var File_remote_proto protoreflect.FileDescriptor

const file_remote_proto_rawDesc = "" +
	"\n" +
	"\fremote.proto\x12\x04lugo\x1a\rphysics.proto\x1a\fserver.proto\"\x14\n" +
	"\x12PauseResumeRequest\"\x11\n" +
	"\x0fNextTurnRequest\"\x12\n" +
	"\x10NextOrderRequest\"\x8b\x01\n" +
	"\x0eBallProperties\x12'\n" +
	"\bposition\x18\x01 \x01(\v2\v.lugo.PointR\bposition\x12*\n" +
	"\bvelocity\x18\x02 \x01(\v2\x0e.lugo.VelocityR\bvelocity\x12$\n" +
	"\x06holder\x18\x03 \x01(\v2\f.lugo.PlayerR\x06holder\"\xa4\x01\n" +
	"\x10PlayerProperties\x12#\n" +
	"\x04side\x18\x01 \x01(\x0e2\x0f.lugo.Team.SideR\x04side\x12\x16\n" +
	"\x06number\x18\x02 \x01(\rR\x06number\x12'\n" +
	"\bposition\x18\x03 \x01(\v2\v.lugo.PointR\bposition\x12*\n" +
	"\bvelocity\x18\x04 \x01(\v2\x0e.lugo.VelocityR\bvelocity\"\xb9\x01\n" +
	"\x0eGameProperties\x12\x12\n" +
	"\x04turn\x18\x01 \x01(\rR\x04turn\x12\x1d\n" +
	"\n" +
	"home_score\x18\x02 \x01(\rR\thomeScore\x12\x1d\n" +
	"\n" +
	"away_score\x18\x03 \x01(\rR\tawayScore\x12%\n" +
	"\x0eframe_interval\x18\x04 \x01(\x03R\rframeInterval\x12.\n" +
	"\n" +
	"shot_clock\x18\x05 \x01(\v2\x0f.lugo.ShotClockR\tshotClock\"\xea\x01\n" +
	"\x0fCommandResponse\x124\n" +
	"\x04code\x18\x01 \x01(\x0e2 .lugo.CommandResponse.StatusCodeR\x04code\x127\n" +
	"\rgame_snapshot\x18\x02 \x01(\v2\x12.lugo.GameSnapshotR\fgameSnapshot\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"N\n" +
	"\n" +
	"StatusCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x11\n" +
	"\rINVALID_VALUE\x10\x01\x12\x15\n" +
	"\x11DEADLINE_EXCEEDED\x10\x02\x12\t\n" +
	"\x05OTHER\x10c\"\x18\n" +
	"\x16ResumeListeningRequest\"\x19\n" +
	"\x17ResumeListeningResponse\"\x1d\n" +
	"\x1bResetPlayerPositionsRequest\"\x12\n" +
	"\x10ResetGameRequest\"W\n" +
	"\x1cResetPlayerPositionsResponse\x127\n" +
	"\rgame_snapshot\x18\x01 \x01(\v2\x12.lugo.GameSnapshotR\fgameSnapshot\"\x15\n" +
	"\x13GameSnapshotRequest\"O\n" +
	"\x14GameSnapshotResponse\x127\n" +
	"\rgame_snapshot\x18\x01 \x01(\v2\x12.lugo.GameSnapshotR\fgameSnapshot2\xc4\x05\n" +
	"\x06Remote\x12@\n" +
	"\rPauseOrResume\x12\x18.lugo.PauseResumeRequest\x1a\x15.lugo.CommandResponse\x128\n" +
	"\bNextTurn\x12\x15.lugo.NextTurnRequest\x1a\x15.lugo.CommandResponse\x12:\n" +
	"\tNextOrder\x12\x16.lugo.NextOrderRequest\x1a\x15.lugo.CommandResponse\x12@\n" +
	"\x11SetBallProperties\x12\x14.lugo.BallProperties\x1a\x15.lugo.CommandResponse\x12D\n" +
	"\x13SetPlayerProperties\x12\x16.lugo.PlayerProperties\x1a\x15.lugo.CommandResponse\x12@\n" +
	"\x11SetGameProperties\x12\x14.lugo.GameProperties\x1a\x15.lugo.CommandResponse\x12S\n" +
	"\x14ResumeListeningPhase\x12\x1c.lugo.ResumeListeningRequest\x1a\x1d.lugo.ResumeListeningResponse\x12]\n" +
	"\x14ResetPlayerPositions\x12!.lugo.ResetPlayerPositionsRequest\x1a\".lugo.ResetPlayerPositionsResponse\x12:\n" +
	"\tResetGame\x12\x16.lugo.ResetGameRequest\x1a\x15.lugo.CommandResponse\x12H\n" +
	"\x0fGetGameSnapshot\x12\x19.lugo.GameSnapshotRequest\x1a\x1a.lugo.GameSnapshotResponseB#Z!github.com/lugobots/lugo4go/protob\x06proto3"

var (
	file_remote_proto_rawDescOnce sync.Once
	file_remote_proto_rawDescData []byte
)

func file_remote_proto_rawDescGZIP() []byte {
	file_remote_proto_rawDescOnce.Do(func() {
		file_remote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remote_proto_rawDesc), len(file_remote_proto_rawDesc)))
	})
	return file_remote_proto_rawDescData
}

var file_remote_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_remote_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_remote_proto_goTypes = []any{
	(CommandResponse_StatusCode)(0),      // 0: lugo.CommandResponse.StatusCode
	(*PauseResumeRequest)(nil),           // 1: lugo.PauseResumeRequest
	(*NextTurnRequest)(nil),              // 2: lugo.NextTurnRequest
	(*NextOrderRequest)(nil),             // 3: lugo.NextOrderRequest
	(*BallProperties)(nil),               // 4: lugo.BallProperties
	(*PlayerProperties)(nil),             // 5: lugo.PlayerProperties
	(*GameProperties)(nil),               // 6: lugo.GameProperties
	(*CommandResponse)(nil),              // 7: lugo.CommandResponse
	(*ResumeListeningRequest)(nil),       // 8: lugo.ResumeListeningRequest
	(*ResumeListeningResponse)(nil),      // 9: lugo.ResumeListeningResponse
	(*ResetPlayerPositionsRequest)(nil),  // 10: lugo.ResetPlayerPositionsRequest
	(*ResetGameRequest)(nil),             // 11: lugo.ResetGameRequest
	(*ResetPlayerPositionsResponse)(nil), // 12: lugo.ResetPlayerPositionsResponse
	(*GameSnapshotRequest)(nil),          // 13: lugo.GameSnapshotRequest
	(*GameSnapshotResponse)(nil),         // 14: lugo.GameSnapshotResponse
	(*Point)(nil),                        // 15: lugo.Point
	(*Velocity)(nil),                     // 16: lugo.Velocity
	(*Player)(nil),                       // 17: lugo.Player
	(Team_Side)(0),                       // 18: lugo.Team.Side
	(*ShotClock)(nil),                    // 19: lugo.ShotClock
	(*GameSnapshot)(nil),                 // 20: lugo.GameSnapshot
}
var file_remote_proto_depIdxs = []int32{
	15, // 0: lugo.BallProperties.position:type_name -> lugo.Point
	16, // 1: lugo.BallProperties.velocity:type_name -> lugo.Velocity
	17, // 2: lugo.BallProperties.holder:type_name -> lugo.Player
	18, // 3: lugo.PlayerProperties.side:type_name -> lugo.Team.Side
	15, // 4: lugo.PlayerProperties.position:type_name -> lugo.Point
	16, // 5: lugo.PlayerProperties.velocity:type_name -> lugo.Velocity
	19, // 6: lugo.GameProperties.shot_clock:type_name -> lugo.ShotClock
	0,  // 7: lugo.CommandResponse.code:type_name -> lugo.CommandResponse.StatusCode
	20, // 8: lugo.CommandResponse.game_snapshot:type_name -> lugo.GameSnapshot
	20, // 9: lugo.ResetPlayerPositionsResponse.game_snapshot:type_name -> lugo.GameSnapshot
	20, // 10: lugo.GameSnapshotResponse.game_snapshot:type_name -> lugo.GameSnapshot
	1,  // 11: lugo.Remote.PauseOrResume:input_type -> lugo.PauseResumeRequest
	2,  // 12: lugo.Remote.NextTurn:input_type -> lugo.NextTurnRequest
	3,  // 13: lugo.Remote.NextOrder:input_type -> lugo.NextOrderRequest
	4,  // 14: lugo.Remote.SetBallProperties:input_type -> lugo.BallProperties
	5,  // 15: lugo.Remote.SetPlayerProperties:input_type -> lugo.PlayerProperties
	6,  // 16: lugo.Remote.SetGameProperties:input_type -> lugo.GameProperties
	8,  // 17: lugo.Remote.ResumeListeningPhase:input_type -> lugo.ResumeListeningRequest
	10, // 18: lugo.Remote.ResetPlayerPositions:input_type -> lugo.ResetPlayerPositionsRequest
	11, // 19: lugo.Remote.ResetGame:input_type -> lugo.ResetGameRequest
	13, // 20: lugo.Remote.GetGameSnapshot:input_type -> lugo.GameSnapshotRequest
	7,  // 21: lugo.Remote.PauseOrResume:output_type -> lugo.CommandResponse
	7,  // 22: lugo.Remote.NextTurn:output_type -> lugo.CommandResponse
	7,  // 23: lugo.Remote.NextOrder:output_type -> lugo.CommandResponse
	7,  // 24: lugo.Remote.SetBallProperties:output_type -> lugo.CommandResponse
	7,  // 25: lugo.Remote.SetPlayerProperties:output_type -> lugo.CommandResponse
	7,  // 26: lugo.Remote.SetGameProperties:output_type -> lugo.CommandResponse
	9,  // 27: lugo.Remote.ResumeListeningPhase:output_type -> lugo.ResumeListeningResponse
	12, // 28: lugo.Remote.ResetPlayerPositions:output_type -> lugo.ResetPlayerPositionsResponse
	7,  // 29: lugo.Remote.ResetGame:output_type -> lugo.CommandResponse
	14, // 30: lugo.Remote.GetGameSnapshot:output_type -> lugo.GameSnapshotResponse
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_remote_proto_init() }
func file_remote_proto_init() {
	if File_remote_proto != nil {
		return
	}
	file_physics_proto_init()
	file_server_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remote_proto_rawDesc), len(file_remote_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remote_proto_goTypes,
		DependencyIndexes: file_remote_proto_depIdxs,
		EnumInfos:         file_remote_proto_enumTypes,
		MessageInfos:      file_remote_proto_msgTypes,
	}.Build()
	File_remote_proto = out.File
	file_remote_proto_goTypes = nil
	file_remote_proto_depIdxs = nil
}
