// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.27.1
// source: rl_assistant.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RLSessionConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RLSessionConfig) Reset() {
	*x = RLSessionConfig{}
	mi := &file_rl_assistant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RLSessionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RLSessionConfig) ProtoMessage() {}

func (x *RLSessionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_rl_assistant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RLSessionConfig.ProtoReflect.Descriptor instead.
func (*RLSessionConfig) Descriptor() ([]byte, []int) {
	return file_rl_assistant_proto_rawDescGZIP(), []int{0}
}

type PlayerOrdersOnRLSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identify the bot's team side (Team_Home or Team_Away)
	TeamSide Team_Side `protobuf:"varint,1,opt,name=team_side,json=teamSide,proto3,enum=lugo.Team_Side" json:"team_side,omitempty"`
	// Player's number 1-11
	Number uint32 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	// if  behaviour is not set, the orders will be executed
	Behaviour     string   `protobuf:"bytes,3,opt,name=behaviour,proto3" json:"behaviour,omitempty"`
	Orders        []*Order `protobuf:"bytes,4,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerOrdersOnRLSession) Reset() {
	*x = PlayerOrdersOnRLSession{}
	mi := &file_rl_assistant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerOrdersOnRLSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOrdersOnRLSession) ProtoMessage() {}

func (x *PlayerOrdersOnRLSession) ProtoReflect() protoreflect.Message {
	mi := &file_rl_assistant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOrdersOnRLSession.ProtoReflect.Descriptor instead.
func (*PlayerOrdersOnRLSession) Descriptor() ([]byte, []int) {
	return file_rl_assistant_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerOrdersOnRLSession) GetTeamSide() Team_Side {
	if x != nil {
		return x.TeamSide
	}
	return Team_HOME
}

func (x *PlayerOrdersOnRLSession) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *PlayerOrdersOnRLSession) GetBehaviour() string {
	if x != nil {
		return x.Behaviour
	}
	return ""
}

func (x *PlayerOrdersOnRLSession) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type PlayersOrders struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	DefaultBehaviour string                     `protobuf:"bytes,1,opt,name=default_behaviour,json=defaultBehaviour,proto3" json:"default_behaviour,omitempty"`
	PlayersOrders    []*PlayerOrdersOnRLSession `protobuf:"bytes,2,rep,name=players_orders,json=playersOrders,proto3" json:"players_orders,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlayersOrders) Reset() {
	*x = PlayersOrders{}
	mi := &file_rl_assistant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayersOrders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayersOrders) ProtoMessage() {}

func (x *PlayersOrders) ProtoReflect() protoreflect.Message {
	mi := &file_rl_assistant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayersOrders.ProtoReflect.Descriptor instead.
func (*PlayersOrders) Descriptor() ([]byte, []int) {
	return file_rl_assistant_proto_rawDescGZIP(), []int{2}
}

func (x *PlayersOrders) GetDefaultBehaviour() string {
	if x != nil {
		return x.DefaultBehaviour
	}
	return ""
}

func (x *PlayersOrders) GetPlayersOrders() []*PlayerOrdersOnRLSession {
	if x != nil {
		return x.PlayersOrders
	}
	return nil
}

type TurnOutcome struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	GameSnapshot         *GameSnapshot          `protobuf:"bytes,1,opt,name=game_snapshot,json=gameSnapshot,proto3" json:"game_snapshot,omitempty"`
	ScoreChanged         bool                   `protobuf:"varint,2,opt,name=score_changed,json=scoreChanged,proto3" json:"score_changed,omitempty"`
	ShotClockExpired     bool                   `protobuf:"varint,3,opt,name=shot_clock_expired,json=shotClockExpired,proto3" json:"shot_clock_expired,omitempty"`
	GoalZoneTimerExpired bool                   `protobuf:"varint,4,opt,name=goal_zone_timer_expired,json=goalZoneTimerExpired,proto3" json:"goal_zone_timer_expired,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TurnOutcome) Reset() {
	*x = TurnOutcome{}
	mi := &file_rl_assistant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnOutcome) ProtoMessage() {}

func (x *TurnOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_rl_assistant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnOutcome.ProtoReflect.Descriptor instead.
func (*TurnOutcome) Descriptor() ([]byte, []int) {
	return file_rl_assistant_proto_rawDescGZIP(), []int{3}
}

func (x *TurnOutcome) GetGameSnapshot() *GameSnapshot {
	if x != nil {
		return x.GameSnapshot
	}
	return nil
}

func (x *TurnOutcome) GetScoreChanged() bool {
	if x != nil {
		return x.ScoreChanged
	}
	return false
}

func (x *TurnOutcome) GetShotClockExpired() bool {
	if x != nil {
		return x.ShotClockExpired
	}
	return false
}

func (x *TurnOutcome) GetGoalZoneTimerExpired() bool {
	if x != nil {
		return x.GoalZoneTimerExpired
	}
	return false
}

type RLResetConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RLResetConfig) Reset() {
	*x = RLResetConfig{}
	mi := &file_rl_assistant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RLResetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RLResetConfig) ProtoMessage() {}

func (x *RLResetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_rl_assistant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RLResetConfig.ProtoReflect.Descriptor instead.
func (*RLResetConfig) Descriptor() ([]byte, []int) {
	return file_rl_assistant_proto_rawDescGZIP(), []int{4}
}

var File_rl_assistant_proto protoreflect.FileDescriptor

const file_rl_assistant_proto_rawDesc = "" +
	"\n" +
	"\x12rl_assistant.proto\x12\x04lugo\x1a\fserver.proto\"\x11\n" +
	"\x0fRLSessionConfig\"\xa2\x01\n" +
	"\x17PlayerOrdersOnRLSession\x12,\n" +
	"\tteam_side\x18\x01 \x01(\x0e2\x0f.lugo.Team.SideR\bteamSide\x12\x16\n" +
	"\x06number\x18\x02 \x01(\rR\x06number\x12\x1c\n" +
	"\tbehaviour\x18\x03 \x01(\tR\tbehaviour\x12#\n" +
	"\x06orders\x18\x04 \x03(\v2\v.lugo.OrderR\x06orders\"\x82\x01\n" +
	"\rPlayersOrders\x12+\n" +
	"\x11default_behaviour\x18\x01 \x01(\tR\x10defaultBehaviour\x12D\n" +
	"\x0eplayers_orders\x18\x02 \x03(\v2\x1d.lugo.PlayerOrdersOnRLSessionR\rplayersOrders\"\xd0\x01\n" +
	"\vTurnOutcome\x127\n" +
	"\rgame_snapshot\x18\x01 \x01(\v2\x12.lugo.GameSnapshotR\fgameSnapshot\x12#\n" +
	"\rscore_changed\x18\x02 \x01(\bR\fscoreChanged\x12,\n" +
	"\x12shot_clock_expired\x18\x03 \x01(\bR\x10shotClockExpired\x125\n" +
	"\x17goal_zone_timer_expired\x18\x04 \x01(\bR\x14goalZoneTimerExpired\"\x0f\n" +
	"\rRLResetConfig2\xbb\x01\n" +
	"\vRLAssistant\x12;\n" +
	"\fStartSession\x12\x15.lugo.RLSessionConfig\x1a\x12.lugo.GameSnapshot0\x01\x12;\n" +
	"\x11SendPlayersOrders\x12\x13.lugo.PlayersOrders\x1a\x11.lugo.TurnOutcome\x122\n" +
	"\bResetEnv\x12\x13.lugo.RLResetConfig\x1a\x11.lugo.TurnOutcomeB#Z!github.com/lugobots/lugo4go/protob\x06proto3"

var (
	file_rl_assistant_proto_rawDescOnce sync.Once
	file_rl_assistant_proto_rawDescData []byte
)

func file_rl_assistant_proto_rawDescGZIP() []byte {
	file_rl_assistant_proto_rawDescOnce.Do(func() {
		file_rl_assistant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rl_assistant_proto_rawDesc), len(file_rl_assistant_proto_rawDesc)))
	})
	return file_rl_assistant_proto_rawDescData
}

var file_rl_assistant_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rl_assistant_proto_goTypes = []any{
	(*RLSessionConfig)(nil),         // 0: lugo.RLSessionConfig
	(*PlayerOrdersOnRLSession)(nil), // 1: lugo.PlayerOrdersOnRLSession
	(*PlayersOrders)(nil),           // 2: lugo.PlayersOrders
	(*TurnOutcome)(nil),             // 3: lugo.TurnOutcome
	(*RLResetConfig)(nil),           // 4: lugo.RLResetConfig
	(Team_Side)(0),                  // 5: lugo.Team.Side
	(*Order)(nil),                   // 6: lugo.Order
	(*GameSnapshot)(nil),            // 7: lugo.GameSnapshot
}
var file_rl_assistant_proto_depIdxs = []int32{
	5, // 0: lugo.PlayerOrdersOnRLSession.team_side:type_name -> lugo.Team.Side
	6, // 1: lugo.PlayerOrdersOnRLSession.orders:type_name -> lugo.Order
	1, // 2: lugo.PlayersOrders.players_orders:type_name -> lugo.PlayerOrdersOnRLSession
	7, // 3: lugo.TurnOutcome.game_snapshot:type_name -> lugo.GameSnapshot
	0, // 4: lugo.RLAssistant.StartSession:input_type -> lugo.RLSessionConfig
	2, // 5: lugo.RLAssistant.SendPlayersOrders:input_type -> lugo.PlayersOrders
	4, // 6: lugo.RLAssistant.ResetEnv:input_type -> lugo.RLResetConfig
	7, // 7: lugo.RLAssistant.StartSession:output_type -> lugo.GameSnapshot
	3, // 8: lugo.RLAssistant.SendPlayersOrders:output_type -> lugo.TurnOutcome
	3, // 9: lugo.RLAssistant.ResetEnv:output_type -> lugo.TurnOutcome
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rl_assistant_proto_init() }
func file_rl_assistant_proto_init() {
	if File_rl_assistant_proto != nil {
		return
	}
	file_server_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rl_assistant_proto_rawDesc), len(file_rl_assistant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rl_assistant_proto_goTypes,
		DependencyIndexes: file_rl_assistant_proto_depIdxs,
		MessageInfos:      file_rl_assistant_proto_msgTypes,
	}.Build()
	File_rl_assistant_proto = out.File
	file_rl_assistant_proto_goTypes = nil
	file_rl_assistant_proto_depIdxs = nil
}
